schema-version: 2.0.2

package:
  name: apisix-ingress-controller

advisories:
  - id: CGA-j3w5-9495-j48j
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2025-07-02T10:51:27Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: 9a4ad4f611fb9484
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - type: pending-upstream-fix
        data:
          note: 'The apisix-ingress-controller cannot be rebuilt with the latest protobuf due to usage of deprecated symbols from `github.com/golang/protobuf`. Upstream needs to migrate to `google.golang.org/protobuf` and regenerate `.pb.go` files to unblock CVE fixes via dependency updates.'
