schema-version: 2.0.2

package:
  name: apisix-ingress-controller

advisories:
  - id: CGA-452f-wh3f-rv83
    aliases:
      - CVE-2025-58181
      - GHSA-j5w8-q4qc-rx2x
    events:
      - timestamp: 2025-11-21T07:30:16Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: 66fd78985ab67a72
            componentName: golang.org/x/crypto
            componentVersion: v0.36.0
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-21T09:30:32Z
        type: fixed
        data:
          fixed-version: 1.8.4-r5

  - id: CGA-4xjg-frw7-h6xv
    aliases:
      - CVE-2025-58187
      - GHSA-frhw-mqj2-wxw2
    events:
      - timestamp: 2025-11-02T09:23:34Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:43Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-5jq4-xgx9-hv94
    aliases:
      - CVE-2025-47912
      - GHSA-447v-2qg4-h8hc
    events:
      - timestamp: 2025-11-02T09:23:32Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:44Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-5rm6-54fc-x3p2
    aliases:
      - CVE-2025-58185
      - GHSA-jwmf-chvc-rf92
    events:
      - timestamp: 2025-11-02T09:23:33Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:45Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-7h49-mr4x-2f35
    aliases:
      - CVE-2025-61725
      - GHSA-qh38-484v-w52x
    events:
      - timestamp: 2025-11-02T09:23:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:45Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-839w-hcf8-4wc8
    aliases:
      - CVE-2025-58186
      - GHSA-rjcg-56ph-3qvg
    events:
      - timestamp: 2025-11-02T09:23:33Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:46Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-gw49-2jjq-352h
    aliases:
      - CVE-2025-61724
      - GHSA-wcw9-47fp-rrfr
    events:
      - timestamp: 2025-11-02T09:23:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:46Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-hv92-35q8-f3cj
    aliases:
      - CVE-2025-47907
      - GHSA-j5pm-7495-qmr3
    events:
      - timestamp: 2025-08-10T05:51:18Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: a3d0357fcfddf7c1
            componentName: stdlib
            componentVersion: go1.24.5
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-08-10T15:42:39Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Govulncheck found no affected symbols in the scanned Go binaries.

  - id: CGA-j3w5-9495-j48j
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2025-07-02T10:51:27Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: 9a4ad4f611fb9484
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-07-02T11:04:00Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Govulncheck found no affected symbols in the scanned Go binaries.
      - timestamp: 2025-07-07T10:51:27Z
        type: pending-upstream-fix
        data:
          note: The apisix-ingress-controller cannot be rebuilt with the latest protobuf due to usage of deprecated symbols from `github.com/golang/protobuf`. Upstream needs to migrate to `google.golang.org/protobuf` and regenerate `.pb.go` files to unblock CVE fixes via dependency updates.

  - id: CGA-mh9f-rf28-4rwh
    aliases:
      - CVE-2025-58189
      - GHSA-cxq7-xw9v-rcv3
    events:
      - timestamp: 2025-11-02T09:23:35Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:47Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-pmm9-mr6v-j8vw
    aliases:
      - CVE-2025-47914
      - GHSA-f6x5-jh6r-wrfv
    events:
      - timestamp: 2025-11-21T07:30:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: 66fd78985ab67a72
            componentName: golang.org/x/crypto
            componentVersion: v0.36.0
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-21T09:30:33Z
        type: fixed
        data:
          fixed-version: 1.8.4-r5

  - id: CGA-pmvp-qp7m-m656
    aliases:
      - CVE-2025-61723
      - GHSA-hjx7-fpxx-mj48
    events:
      - timestamp: 2025-11-02T09:23:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:47Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-q2p7-vr52-p3r2
    aliases:
      - CVE-2025-61729
      - GHSA-7c64-f9jr-v9h2
    events:
      - timestamp: 2025-12-04T11:07:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: a726c72b630b1d19
            componentName: stdlib
            componentVersion: go1.25.4
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-12-04T17:12:52Z
        type: fixed
        data:
          fixed-version: 1.8.4-r6

  - id: CGA-q78w-c2jh-vhr6
    aliases:
      - CVE-2025-58183
      - GHSA-9gcr-gp5f-jw27
    events:
      - timestamp: 2025-11-02T09:23:33Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:48Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4

  - id: CGA-wxpw-x7vf-7qfr
    aliases:
      - CVE-2025-58188
      - GHSA-7wwx-xj66-r44x
    events:
      - timestamp: 2025-11-02T09:23:35Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: apisix-ingress-controller
            componentID: c79ec787d342b101
            componentName: stdlib
            componentVersion: go1.24.6
            componentType: go-module
            componentLocation: /usr/bin/apisix-ingress-controller
            scanner: grype
      - timestamp: 2025-11-02T14:29:48Z
        type: fixed
        data:
          fixed-version: 1.8.4-r4
