schema-version: 2.0.2

package:
  name: aws-application-networking-k8s

advisories:
  - id: CGA-32x6-p9xc-537h
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-02-01T22:05:11Z
        type: fixed
        data:
          fixed-version: 1.1.0-r2

  - id: CGA-42pv-v5pr-vpx8
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-02-01T22:05:10Z
        type: fixed
        data:
          fixed-version: 1.1.0-r2

  - id: CGA-5hqh-4xg6-qwrw
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-03-13T20:44:22Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: aws-application-networking-k8s
            componentID: 1c3c95626b7cca54
            componentName: golang.org/x/net
            componentVersion: v0.33.0
            componentType: go-module
            componentLocation: /usr/bin/manager
            scanner: grype
      - timestamp: 2025-03-14T17:17:22Z
        type: fixed
        data:
          fixed-version: 1.1.0-r5

  - id: CGA-7hw8-r3vp-j7rf
    aliases:
      - CVE-2025-22871
      - GHSA-g9pc-8g42-g6vq
    events:
      - timestamp: 2025-04-10T08:36:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: aws-application-networking-k8s
            componentID: 18d140c00045afa0
            componentName: stdlib
            componentVersion: go1.24.1
            componentType: go-module
            componentLocation: /usr/bin/manager
            scanner: grype
      - timestamp: 2025-04-10T14:21:16Z
        type: fixed
        data:
          fixed-version: 1.1.0-r6

  - id: CGA-j32h-28jw-9m9v
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T07:07:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: aws-application-networking-k8s
            componentID: 1a69b2ffc0b2e2ef
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/manager
            scanner: grype
      - timestamp: 2025-02-08T16:45:36Z
        type: fixed
        data:
          fixed-version: 1.1.0-r3

  - id: CGA-pwjw-j294-24qr
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T07:09:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: aws-application-networking-k8s
            componentID: ab75254f02078bd3
            componentName: golang.org/x/net
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/manager
            scanner: grype
      - timestamp: 2024-12-20T07:11:45Z
        type: fixed
        data:
          fixed-version: 1.1.0-r1

  - id: CGA-v7p5-25mc-4295
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T06:32:54Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: aws-application-networking-k8s
            componentID: 4383fd872caef48f
            componentName: golang.org/x/oauth2
            componentVersion: v0.22.0
            componentType: go-module
            componentLocation: /usr/bin/manager
            scanner: grype
      - timestamp: 2025-03-12T16:31:36Z
        type: fixed
        data:
          fixed-version: 1.1.0-r4
