schema-version: 2.0.2

package:
  name: configmap-reload

advisories:
  - id: CVE-2023-39326
    aliases:
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-22T07:50:49Z
        type: fixed
        data:
          fixed-version: 0.12.0-r3

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:24:48Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:24:49Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45285
    aliases:
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-22T07:50:49Z
        type: fixed
        data:
          fixed-version: 0.12.0-r3

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:09:27Z
        type: fixed
        data:
          fixed-version: 0.12.0-r6

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T07:14:21Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T07:14:21Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T07:14:22Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T07:14:23Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T07:14:20Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:19:58Z
        type: fixed
        data:
          fixed-version: 0.12.0-r5

  - id: CVE-2024-24787
    aliases:
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:07:57Z
        type: fixed
        data:
          fixed-version: 0.13.0-r1
