schema-version: 2.0.2

package:
  name: configmap-reload

advisories:
  - id: CGA-2j5w-25m2-3p2h
    aliases:
      - CVE-2023-39326
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-22T07:50:49Z
        type: fixed
        data:
          fixed-version: 0.12.0-r3

  - id: CGA-54m3-qc75-h9qq
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T13:07:59Z
        type: fixed
        data:
          fixed-version: 0.13.0-r1

  - id: CGA-5cmr-4p39-j9rx
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:19:58Z
        type: fixed
        data:
          fixed-version: 0.12.0-r5

  - id: CGA-7rxw-4f7q-ph8w
    aliases:
      - CVE-2023-45285
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-22T07:50:49Z
        type: fixed
        data:
          fixed-version: 0.12.0-r3

  - id: CGA-99gq-8jwp-298w
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T07:38:31Z
        type: fixed
        data:
          fixed-version: 0.13.0-r2

  - id: CGA-c2p5-fc85-c8r7
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T07:14:23Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-cqfh-5x63-289v
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:24:49Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-mg8j-h498-qr7p
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T07:14:22Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-mvh2-f7wj-r532
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:09:27Z
        type: fixed
        data:
          fixed-version: 0.12.0-r6

  - id: CGA-r694-5669-5647
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T07:14:21Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-r6qv-7g79-xhr3
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:24:48Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-r8vm-3ww4-g8wf
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T07:14:20Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-rj4x-q2qq-g62c
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T07:14:21Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-rrrh-j687-86v2
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:07:57Z
        type: fixed
        data:
          fixed-version: 0.13.0-r1
