schema-version: 2.0.2

package:
  name: configmap-reload

advisories:
  - id: CGA-2j5w-25m2-3p2h
    aliases:
      - CVE-2023-39326
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-22T07:50:49Z
        type: fixed
        data:
          fixed-version: 0.12.0-r3

  - id: CGA-54m3-qc75-h9qq
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T13:07:59Z
        type: fixed
        data:
          fixed-version: 0.13.0-r1

  - id: CGA-5cmr-4p39-j9rx
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:19:58Z
        type: fixed
        data:
          fixed-version: 0.12.0-r5

  - id: CGA-774w-w398-qj3p
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T07:42:32Z
        type: fixed
        data:
          fixed-version: 0.14.0-r2

  - id: CGA-7rxw-4f7q-ph8w
    aliases:
      - CVE-2023-45285
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-22T07:50:49Z
        type: fixed
        data:
          fixed-version: 0.12.0-r3

  - id: CGA-99gq-8jwp-298w
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T07:38:31Z
        type: fixed
        data:
          fixed-version: 0.13.0-r2

  - id: CGA-c2p5-fc85-c8r7
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T07:14:23Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-cqfh-5x63-289v
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:24:49Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-hpq2-wfrp-9ffv
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T23:02:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: configmap-reload
            componentID: 98cf02fce177af3d
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/configmap-reload
            scanner: grype
      - timestamp: 2024-09-12T18:37:05Z
        type: fixed
        data:
          fixed-version: 0.13.1-r2

  - id: CGA-mg8j-h498-qr7p
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T07:14:22Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-mvh2-f7wj-r532
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:09:27Z
        type: fixed
        data:
          fixed-version: 0.12.0-r6

  - id: CGA-pc66-8cc5-786j
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T07:16:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: configmap-reload
            componentID: 836d4a42129858cd
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/configmap-reload
            scanner: grype
      - timestamp: 2025-02-08T21:35:34Z
        type: fixed
        data:
          fixed-version: 0.14.0-r3

  - id: CGA-pg53-rj3r-x6f6
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T23:02:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: configmap-reload
            componentID: 98cf02fce177af3d
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/configmap-reload
            scanner: grype
      - timestamp: 2024-09-12T18:37:06Z
        type: fixed
        data:
          fixed-version: 0.13.1-r2

  - id: CGA-r694-5669-5647
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T07:14:21Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-r6qv-487h-6rgf
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T07:38:34Z
        type: fixed
        data:
          fixed-version: 0.13.0-r2

  - id: CGA-r6qv-7g79-xhr3
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:24:48Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-r8vm-3ww4-g8wf
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T07:14:20Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-rj4x-q2qq-g62c
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T07:14:21Z
        type: fixed
        data:
          fixed-version: 0.12.0-r4

  - id: CGA-rqj8-wxcr-8gwg
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T07:42:37Z
        type: fixed
        data:
          fixed-version: 0.14.0-r2

  - id: CGA-rrrh-j687-86v2
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:07:57Z
        type: fixed
        data:
          fixed-version: 0.13.0-r1

  - id: CGA-w7v6-2xxh-mrgf
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T08:31:51Z
        type: fixed
        data:
          fixed-version: 0.13.1-r1

  - id: CGA-wcfw-mfj3-mg9p
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T23:02:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: configmap-reload
            componentID: 98cf02fce177af3d
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/configmap-reload
            scanner: grype
      - timestamp: 2024-09-12T18:37:04Z
        type: fixed
        data:
          fixed-version: 0.13.1-r2
