schema-version: 2.0.2

package:
  name: docker-compose

advisories:
  - id: CGA-2q2m-jhm7-f5xc
    aliases:
      - CVE-2024-29018
      - GHSA-mq39-4gv4-mvpx
    events:
      - timestamp: 2024-03-21T07:07:17Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 0b3ad6c647777761
            componentName: github.com/docker/docker
            componentVersion: v25.0.4-0.20240301160236-51e876cd964c+incompatible
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-03-21T11:44:19Z
        type: fixed
        data:
          fixed-version: 2.25.0-r2

  - id: CGA-3m34-qj42-9r8x
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T20:14:48Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 2e2c4e8d1f7cbf1c
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-09-12T16:23:46Z
        type: fixed
        data:
          fixed-version: 2.29.3-r0

  - id: CGA-6jqm-chpx-gm57
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:06:25Z
        type: fixed
        data:
          fixed-version: 2.26.1-r1

  - id: CGA-7524-xgqq-fm4r
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T20:28:27Z
        type: fixed
        data:
          fixed-version: 2.32.4-r1

  - id: CGA-78hf-3hq6-7j44
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T10:08:53Z
        type: fixed
        data:
          fixed-version: 2.27.0-r1

  - id: CGA-7xh6-4vjw-xjqc
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2024-07-31T09:27:31Z
        type: fixed
        data:
          fixed-version: 2.29.1-r0

  - id: CGA-8hrr-jxm5-vpwx
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-13T09:02:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 27339689815c8f31
            componentName: golang.org/x/crypto
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-12-13T11:42:29Z
        type: fixed
        data:
          fixed-version: 2.32.0-r0

  - id: CGA-9whg-332v-jwx2
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T17:23:44Z
        type: fixed
        data:
          fixed-version: 2.27.1-r1

  - id: CGA-cwcq-95rv-8435
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-03-14T07:34:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: ad2399d64c2bf1a0
            componentName: golang.org/x/net
            componentVersion: v0.33.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2025-03-16T00:38:00Z
        type: fixed
        data:
          fixed-version: 2.33.1-r3

  - id: CGA-f84x-8q7m-9f23
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T20:14:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 2e2c4e8d1f7cbf1c
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-09-12T16:23:45Z
        type: fixed
        data:
          fixed-version: 2.29.3-r0

  - id: CGA-fgff-hm6x-932q
    aliases:
      - CVE-2024-32473
      - GHSA-x84c-p2g9-rqv9
    events:
      - timestamp: 2024-04-19T10:04:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: e4915b25607d29f7
            componentName: github.com/docker/docker
            componentVersion: v26.0.0+incompatible
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-04-22T07:10:35Z
        type: fixed
        data:
          fixed-version: 2.26.1-r2

  - id: CGA-fqp3-6495-5c9x
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T20:28:22Z
        type: fixed
        data:
          fixed-version: 2.32.4-r1

  - id: CGA-h7cg-hmjw-2jg4
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-15T20:40:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 72194fe99eefb8b6
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-03-19T12:28:56Z
        type: fixed
        data:
          fixed-version: 2.25.0-r1

  - id: CGA-hfhj-h8j2-ph8x
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T07:26:17Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 06a5647bd7e46d1d
            componentName: golang.org/x/net
            componentVersion: v0.29.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-12-19T10:44:19Z
        type: fixed
        data:
          fixed-version: 2.32.1-r1

  - id: CGA-hjhh-9m9w-q6r4
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T10:08:54Z
        type: fixed
        data:
          fixed-version: 2.27.0-r1

  - id: CGA-q2fx-5c6h-528f
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T19:30:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 80af6a485448f40d
            componentName: golang.org/x/oauth2
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2025-03-12T18:06:21Z
        type: fixed
        data:
          fixed-version: 2.33.1-r2

  - id: CGA-vj76-69cw-fvcp
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T07:09:06Z
        type: fixed
        data:
          fixed-version: 2.28.1-r1

  - id: CGA-vwc2-jf2w-fxjp
    aliases:
      - CVE-2023-47108
      - GHSA-8pgv-569h-w5rw
    events:
      - timestamp: 2024-02-14T16:26:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 8ab2a5432a3c73fb
            componentName: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
            componentVersion: v0.45.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-02-21T07:10:19Z
        type: fixed
        data:
          fixed-version: 2.24.6-r0

  - id: CGA-w8g6-q7hf-hq7r
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T20:15:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 2e2c4e8d1f7cbf1c
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-09-12T16:23:46Z
        type: fixed
        data:
          fixed-version: 2.29.3-r0

  - id: CGA-wg55-2xcx-r72p
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T19:30:21Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 1567dce78777615e
            componentName: golang.org/x/crypto
            componentVersion: v0.31.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2025-03-12T08:44:14Z
        type: fixed
        data:
          fixed-version: 2.33.1-r1

  - id: CGA-wpv6-g9cg-5x48
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T19:26:13Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 654911021685f52f
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2025-02-09T19:16:23Z
        type: fixed
        data:
          fixed-version: 2.32.4-r2

  - id: CGA-xp56-4879-9ffg
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T17:23:42Z
        type: fixed
        data:
          fixed-version: 2.27.1-r1
