schema-version: 2.0.2

package:
  name: haproxy-ingress

advisories:
  - id: CGA-3x45-7mr2-xxq2
    aliases:
      - CVE-2020-8552
      - GHSA-82hx-w2r5-c2wq
    events:
      - timestamp: 2023-09-19T16:42:13Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Go vulndb has marked this code NOT_IMPORTABLE.

  - id: CGA-vxw7-cpww-92gj
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-16T18:08:16Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CGA-wxjc-gjpm-fm6f
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-16T18:09:23Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CGA-cxxg-fmvh-x664
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-16T18:11:57Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CGA-p927-hxhg-f45p
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:28:53Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-5q3w-qccf-hwm2
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:28:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-vm7p-7p7r-79x8
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-10T09:02:30Z
        type: fixed
        data:
          fixed-version: 0.14.6-r3

  - id: CGA-v7q2-mc6w-938m
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T09:10:06Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-3hrp-m75c-cp2p
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-13T09:10:07Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-3h9j-rhxp-mwx8
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2023-12-20T02:04:26Z
        type: fixed
        data:
          fixed-version: 0.14.5-r7

  - id: CGA-89wx-p6qv-4c76
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-13T09:10:09Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-rwp3-6wfc-mc5v
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T09:10:04Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-825v-78wx-53cx
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T09:10:05Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-mpw9-hrq7-6384
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:18:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 1cf38f80fe7dd238
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-03-14T15:21:05Z
        type: fixed
        data:
          fixed-version: 0.14.6-r2
