schema-version: 2.0.2

package:
  name: haproxy-ingress

advisories:
  - id: CGA-3g47-gp6x-97c6
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T07:07:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: fffbe6fa2e85c0a3
            componentName: golang.org/x/oauth2
            componentVersion: v0.12.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2025-03-16T06:19:28Z
        type: fixed
        data:
          fixed-version: 0.14.7-r13

  - id: CGA-3h9j-rhxp-mwx8
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2023-12-20T02:04:26Z
        type: fixed
        data:
          fixed-version: 0.14.5-r7

  - id: CGA-3hrp-m75c-cp2p
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-13T09:10:07Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-3x45-7mr2-xxq2
    aliases:
      - CVE-2020-8552
      - GHSA-82hx-w2r5-c2wq
    events:
      - timestamp: 2023-09-19T16:42:13Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Go vulndb has marked this code NOT_IMPORTABLE.

  - id: CGA-5q3w-qccf-hwm2
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:28:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-825v-78wx-53cx
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T09:10:05Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-89wx-p6qv-4c76
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-13T09:10:09Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-9g44-mq22-w7vj
    aliases:
      - CVE-2025-22871
      - GHSA-g9pc-8g42-g6vq
    events:
      - timestamp: 2025-04-10T11:56:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 67d22af740481c18
            componentName: stdlib
            componentVersion: go1.24.1
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype

  - id: CGA-9vcg-qwmx-5354
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T20:10:52Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 5cdde68e0fda2547
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-09-13T05:02:55Z
        type: fixed
        data:
          fixed-version: 0.14.7-r3

  - id: CGA-9w8p-r3q7-2gxm
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T20:10:57Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 5cdde68e0fda2547
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-09-13T05:02:56Z
        type: fixed
        data:
          fixed-version: 0.14.7-r3

  - id: CGA-ccm7-fhf8-5v3v
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-03-14T04:37:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 6df8b29092714926
            componentName: golang.org/x/net
            componentVersion: v0.33.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2025-03-14T20:31:54Z
        type: fixed
        data:
          fixed-version: 0.14.7-r12

  - id: CGA-cm8q-jxpm-pcpm
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T20:06:52Z
        type: fixed
        data:
          fixed-version: 0.14.6-r8

  - id: CGA-cxxg-fmvh-x664
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-16T18:11:57Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CGA-g63g-gpjh-9rg5
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T13:42:56Z
        type: fixed
        data:
          fixed-version: 0.14.7-r7

  - id: CGA-h9m5-48jm-9vjh
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T21:23:35Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: ee01b54df6884885
            componentName: golang.org/x/net
            componentVersion: v0.23.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-12-20T17:29:17Z
        type: fixed
        data:
          fixed-version: 0.14.7-r6

  - id: CGA-jqm4-25gw-8v3q
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T20:06:56Z
        type: fixed
        data:
          fixed-version: 0.14.6-r8

  - id: CGA-mpw9-hrq7-6384
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:18:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 1cf38f80fe7dd238
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-03-14T15:21:05Z
        type: fixed
        data:
          fixed-version: 0.14.6-r2

  - id: CGA-p927-hxhg-f45p
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:28:53Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-p972-8wwx-h3wq
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T07:07:44Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: ed02a9d6c554506a
            componentName: golang.org/x/crypto
            componentVersion: v0.31.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2025-03-11T16:11:35Z
        type: fixed
        data:
          fixed-version: 0.14.7-r10
      - timestamp: 2025-03-14T04:37:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 7f4e545c415750f7
            componentName: golang.org/x/crypto
            componentVersion: v0.31.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2025-03-14T20:31:53Z
        type: fixed
        data:
          fixed-version: 0.14.7-r12

  - id: CGA-pcv9-5h8h-jvgh
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T20:10:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 5cdde68e0fda2547
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-09-13T05:02:55Z
        type: fixed
        data:
          fixed-version: 0.14.7-r3

  - id: CGA-q74j-76mf-72xg
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T18:14:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 831846aa2af78eca
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2025-02-09T15:42:22Z
        type: fixed
        data:
          fixed-version: 0.14.7-r8

  - id: CGA-rwp3-6wfc-mc5v
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T09:10:04Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-v4m6-wvx4-2vh4
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T13:43:02Z
        type: fixed
        data:
          fixed-version: 0.14.7-r7

  - id: CGA-v7q2-mc6w-938m
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T09:10:06Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CGA-vm7p-7p7r-79x8
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-10T09:02:30Z
        type: fixed
        data:
          fixed-version: 0.14.6-r3

  - id: CGA-vxw7-cpww-92gj
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-16T18:08:16Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CGA-wxjc-gjpm-fm6f
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-16T18:09:23Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CGA-x82c-7476-g7mx
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T10:28:20Z
        type: fixed
        data:
          fixed-version: 0.14.7-r1

  - id: CGA-xgmr-6gv2-7qpp
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T08:23:02Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: haproxy-ingress
            componentID: 432cdddca9c606f9
            componentName: golang.org/x/crypto
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/haproxy-ingress-controller
            scanner: grype
      - timestamp: 2024-12-12T14:10:27Z
        type: fixed
        data:
          fixed-version: 0.14.7-r4
