schema-version: 2.0.2

package:
  name: haproxy-ingress

advisories:
  - id: CVE-2020-8552
    aliases:
      - GHSA-82hx-w2r5-c2wq
    events:
      - timestamp: 2023-09-19T16:42:13Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Go vulndb has marked this code NOT_IMPORTABLE.

  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-16T18:08:16Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-16T18:09:23Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-16T18:11:57Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:28:53Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:28:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T09:10:06Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2023-12-20T02:04:26Z
        type: fixed
        data:
          fixed-version: 0.14.5-r7

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T09:10:04Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T09:10:05Z
        type: fixed
        data:
          fixed-version: 0.14.6-r1
