schema-version: 2.0.2

package:
  name: ingress-nginx-controller-1.12

advisories:
  - id: CGA-6grf-wfxw-vjq4
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T14:04:59Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.12
            componentID: 2efe0515e16fdb0e
            componentName: golang.org/x/oauth2
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-ingress-controller
            scanner: grype
      - timestamp: 2025-03-21T18:35:34Z
        type: fixed
        data:
          fixed-version: 1.12.0-r14

  - id: CGA-893v-gwpr-hjcj
    aliases:
      - CVE-2025-1974
      - GHSA-mgvx-rpfc-9mpv
    events:
      - timestamp: 2025-03-26T13:31:17Z
        type: fixed
        data:
          fixed-version: 1.12.1-r14

  - id: CGA-8x6q-2q99-699q
    aliases:
      - CVE-2025-1098
      - GHSA-vg63-w3p9-jc9m
    events:
      - timestamp: 2025-03-26T13:30:51Z
        type: fixed
        data:
          fixed-version: 1.12.1-r14

  - id: CGA-cv23-xfvp-j3jx
    aliases:
      - CVE-2025-22871
      - GHSA-g9pc-8g42-g6vq
    events:
      - timestamp: 2025-04-10T15:45:31Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.12
            componentID: 02b0ea4c5d2d41c0
            componentName: stdlib
            componentVersion: go1.24.1
            componentType: go-module
            componentLocation: /usr/bin/nginx-errors
            scanner: grype
      - timestamp: 2025-04-11T20:03:08Z
        type: fixed
        data:
          fixed-version: 1.12.1-r41

  - id: CGA-f56q-99jf-3jj7
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-03-14T07:44:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.12
            componentID: 51146430ce73fd9b
            componentName: golang.org/x/net
            componentVersion: v0.33.0
            componentType: go-module
            componentLocation: /usr/bin/kube-webhook-certgen
            scanner: grype
      - timestamp: 2025-03-16T05:34:52Z
        type: fixed
        data:
          fixed-version: 1.12.0-r14

  - id: CGA-f9hr-2ppx-hfp7
    aliases:
      - CVE-2025-24514
      - GHSA-fwwp-xcxw-39vq
    events:
      - timestamp: 2025-03-26T13:30:02Z
        type: fixed
        data:
          fixed-version: 1.12.1-r14

  - id: CGA-fg44-rfvp-pvmg
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-09T06:25:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.12
            componentID: 5a7caa6d11b3c3c9
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/kube-webhook-certgen
            scanner: grype
      - timestamp: 2025-02-11T04:06:14Z
        type: fixed
        data:
          fixed-version: 1.12.0-r7

  - id: CGA-w7mg-ppwv-wc8g
    aliases:
      - CVE-2025-24513
      - GHSA-242m-6h72-7hgp
    events:
      - timestamp: 2025-03-26T12:41:46Z
        type: fixed
        data:
          fixed-version: 1.12.1-r14

  - id: CGA-xfjc-qjfg-pg7c
    aliases:
      - CVE-2025-1097
      - GHSA-823x-fv5p-h7hw
    events:
      - timestamp: 2025-03-26T13:30:30Z
        type: fixed
        data:
          fixed-version: 1.12.1-r14
