schema-version: 2.0.2

package:
  name: ingress-nginx-controller-1.14

advisories:
  - id: CGA-frj9-2vj5-63gp
    aliases:
      - CVE-2025-61729
      - GHSA-7c64-f9jr-v9h2
    events:
      - timestamp: 2025-12-05T02:49:45Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.14
            componentID: d36424109522a3f4
            componentName: stdlib
            componentVersion: go1.25.4
            componentType: go-module
            componentLocation: /usr/bin/kube-webhook-certgen
            scanner: grype
      - timestamp: 2025-12-05T13:36:10Z
        type: true-positive-determination
        data:
          note: 'Govulncheck found vulnerable symbols in Go binaries at the following locations: in ingress-nginx-controller-1.14-1.14.0-r1.apk, at usr/bin/nginx-dbg, usr/bin/nginx-dbg, usr/bin/nginx-ingress-controller, usr/bin/nginx-ingress-controller; in ingress-nginx-custom-error-pages-1.14-1.14.0-r1.apk, at usr/bin/nginx-errors, usr/bin/nginx-errors; in kube-webhook-certgen-1.14-1.14.0-r1.apk, at usr/bin/kube-webhook-certgen, usr/bin/kube-webhook-certgen.'
