schema-version: 2.0.2

package:
  name: ingress-nginx-controller-1.14

advisories:
  - id: CGA-frj9-2vj5-63gp
    aliases:
      - CVE-2025-61729
      - GHSA-7c64-f9jr-v9h2
    events:
      - timestamp: 2025-12-05T02:49:45Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: ingress-nginx-controller-1.14
            componentID: d36424109522a3f4
            componentName: stdlib
            componentVersion: go1.25.4
            componentType: go-module
            componentLocation: /usr/bin/kube-webhook-certgen
            scanner: grype
