schema-version: 2.0.2

package:
  name: keycloak-config-cli

advisories:
  - id: CGA-58gj-pw85-8mp5
    aliases:
      - CVE-2025-22233
      - GHSA-4wp7-92pw-q264
    events:
      - timestamp: 2025-06-03T07:42:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: d156053ecd75168d
            componentName: spring-context
            componentVersion: 6.2.3
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli.jar
            scanner: grype
      - timestamp: 2025-06-05T23:02:50Z
        type: fixed
        data:
          fixed-version: 6.4.0-r42

  - id: CGA-5jh2-c8j7-f8m2
    aliases:
      - CVE-2024-10039
      - GHSA-93ww-43rr-79v3
    events:
      - timestamp: 2025-02-27T19:01:00Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:18Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-986w-5q35-929q
    aliases:
      - CVE-2025-7962
      - GHSA-9342-92gg-6v29
    events:
      - timestamp: 2025-08-08T07:29:31Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: 3e9e36daf5b55e73
            componentName: smtp
            componentVersion: 2.0.3
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-08-11T09:17:20Z
        type: fixed
        data:
          fixed-version: 6.4.0-r48

  - id: CGA-9c2v-54pg-2r8h
    aliases:
      - CVE-2025-22228
      - GHSA-mg83-c7gq-rv5c
    events:
      - timestamp: 2025-03-21T07:46:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: 251fd59bd8e65c54
            componentName: spring-security-crypto
            componentVersion: 6.4.3
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-03-22T05:43:02Z
        type: fixed
        data:
          fixed-version: 6.4.0-r3

  - id: CGA-g934-3xgg-h5q9
    aliases:
      - CVE-2024-7318
      - GHSA-xmmm-jw76-q7vg
    events:
      - timestamp: 2025-02-27T19:01:03Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:17Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-pwpx-x8r6-q983
    aliases:
      - CVE-2024-4028
      - GHSA-q4xq-445g-g6ch
    events:
      - timestamp: 2025-02-27T19:01:02Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:17Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-v9jg-xxwx-27jr
    aliases:
      - CVE-2024-7260
      - GHSA-g4gc-rh26-m3p5
    events:
      - timestamp: 2025-02-27T19:01:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:16Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-vcjx-9mrq-qvh3
    aliases:
      - CVE-2025-41249
      - GHSA-jmp9-x22r-554x
    events:
      - timestamp: 2025-09-17T08:14:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: 02cc11cf988f6616
            componentName: spring-core
            componentVersion: 6.2.3
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-09-22T13:57:27Z
        type: fixed
        data:
          fixed-version: 6.4.0-r49

  - id: CGA-x5fq-9fgw-cqhx
    aliases:
      - CVE-2025-22235
      - GHSA-rc42-6c7j-7h5r
    events:
      - timestamp: 2025-04-29T11:53:47Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: 3b422e52e9cd0862
            componentName: spring-boot
            componentVersion: 3.4.3
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli.jar
            scanner: grype
      - timestamp: 2025-05-01T14:26:19Z
        type: pending-upstream-fix
        data:
          note: Any attempts to bump spring-boot to 3.4.5 result in a build failure. We will need for upstream to push a fix and bump the dependency.

  - id: CGA-x6cp-vqf6-p2r9
    aliases:
      - CVE-2025-48924
      - GHSA-j288-q9x7-2f5v
    events:
      - timestamp: 2025-07-12T08:50:00Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: ba9efecc6701b597
            componentName: commons-lang3
            componentVersion: 3.17.0
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli.jar
            scanner: grype
      - timestamp: 2025-07-17T21:02:58Z
        type: fixed
        data:
          fixed-version: 6.4.0-r45
