schema-version: 2.0.2

package:
  name: keycloak-config-cli

advisories:
  - id: CGA-5jh2-c8j7-f8m2
    aliases:
      - CVE-2024-10039
      - GHSA-93ww-43rr-79v3
    events:
      - timestamp: 2025-02-27T19:01:00Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:18Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-9c2v-54pg-2r8h
    aliases:
      - CVE-2025-22228
      - GHSA-mg83-c7gq-rv5c
    events:
      - timestamp: 2025-03-21T07:46:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: 251fd59bd8e65c54
            componentName: spring-security-crypto
            componentVersion: 6.4.3
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-03-22T05:43:02Z
        type: fixed
        data:
          fixed-version: 6.4.0-r3

  - id: CGA-g934-3xgg-h5q9
    aliases:
      - CVE-2024-7318
      - GHSA-xmmm-jw76-q7vg
    events:
      - timestamp: 2025-02-27T19:01:03Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:17Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-pwpx-x8r6-q983
    aliases:
      - CVE-2024-4028
      - GHSA-q4xq-445g-g6ch
    events:
      - timestamp: 2025-02-27T19:01:02Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:17Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1

  - id: CGA-v9jg-xxwx-27jr
    aliases:
      - CVE-2024-7260
      - GHSA-g4gc-rh26-m3p5
    events:
      - timestamp: 2025-02-27T19:01:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: keycloak-config-cli
            componentID: fd01564b3a16b56a
            componentName: keycloak-core
            componentVersion: 24.0.5
            componentType: java-archive
            componentLocation: /usr/share/java/keycloak-config-cli/keycloak-config-cli-24.0.5.jar
            scanner: grype
      - timestamp: 2025-02-27T21:10:16Z
        type: fixed
        data:
          fixed-version: 6.4.0-r1
