schema-version: 2.0.2

package:
  name: kubernetes-ingress-defaultbackend

advisories:
  - id: CGA-2pfw-g2pj-pq6r
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:18:03Z
        type: fixed
        data:
          fixed-version: 1.25.1-r3

  - id: CGA-v6cf-vj8w-xj2h
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:32:17Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-v449-pf34-m8qv
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:32:19Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-3f9g-j4jm-qhvx
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-10T08:53:44Z
        type: fixed
        data:
          fixed-version: 1.28.4-r1

  - id: CGA-jmfj-g2rx-372h
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T11:29:49Z
        type: fixed
        data:
          fixed-version: 1.29.1-r0

  - id: CGA-3qr9-rpvf-hv5r
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T11:29:50Z
        type: fixed
        data:
          fixed-version: 1.29.1-r0
