schema-version: 2.0.2

package:
  name: newrelic-prometheus-configurator

advisories:
  - id: CGA-22mq-62v5-2fwx
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T12:42:22Z
        type: fixed
        data:
          fixed-version: 1.17.0-r1

  - id: CGA-2454-vprx-f582
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T08:13:21Z
        type: fixed
        data:
          fixed-version: 1.14.0-r1

  - id: CGA-3g5m-7fjg-2v78
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T09:24:09Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: newrelic-prometheus-configurator
            componentID: b6303d10c1d18dcb
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-configurator
            scanner: grype
      - timestamp: 2024-09-13T04:03:43Z
        type: fixed
        data:
          fixed-version: 1.17.3-r1

  - id: CGA-4j9q-5254-ghh6
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T09:24:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: newrelic-prometheus-configurator
            componentID: b6303d10c1d18dcb
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-configurator
            scanner: grype
      - timestamp: 2024-09-13T04:03:42Z
        type: fixed
        data:
          fixed-version: 1.17.3-r1

  - id: CGA-4p8g-c9wg-697m
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:33:51Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-6259-wf7f-wf8c
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-15T12:27:45Z
        type: fixed
        data:
          fixed-version: 1.16.0-r1

  - id: CGA-644h-phr4-hjgh
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T08:13:20Z
        type: fixed
        data:
          fixed-version: 1.14.0-r1

  - id: CGA-8v2f-x93p-4c7j
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T13:23:08Z
        type: fixed
        data:
          fixed-version: 1.16.2-r1

  - id: CGA-9hpr-g643-fh28
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-15T12:27:44Z
        type: fixed
        data:
          fixed-version: 1.16.0-r1

  - id: CGA-c8cv-87mj-56hj
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:33:52Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-crp3-jmhq-f723
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:13:20Z
        type: fixed
        data:
          fixed-version: 1.14.0-r1

  - id: CGA-fqjp-jpc6-8r4p
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:21:30Z
        type: fixed
        data:
          fixed-version: 1.15.0-r1

  - id: CGA-g7x5-5q7j-mr6g
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T13:23:11Z
        type: fixed
        data:
          fixed-version: 1.16.2-r1

  - id: CGA-mf4h-2568-wrwf
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T08:13:19Z
        type: fixed
        data:
          fixed-version: 1.14.0-r1

  - id: CGA-mwp2-2mxq-w75v
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-09T01:42:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: newrelic-prometheus-configurator
            componentID: 483cf0ae773629c3
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-configurator
            scanner: grype

  - id: CGA-vr6c-q23x-xx56
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T08:13:19Z
        type: fixed
        data:
          fixed-version: 1.14.0-r1

  - id: CGA-w3w9-rvhq-cp43
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T09:24:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: newrelic-prometheus-configurator
            componentID: b6303d10c1d18dcb
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-configurator
            scanner: grype
      - timestamp: 2024-09-13T04:03:43Z
        type: fixed
        data:
          fixed-version: 1.17.3-r1
