schema-version: 2.0.2

package:
  name: nginx-prometheus-exporter

advisories:
  - id: CGA-5hxx-f2fc-v86g
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-03-14T08:03:52Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 1b8cec5c42ddd219
            componentName: golang.org/x/net
            componentVersion: v0.34.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-03-14T22:15:34Z
        type: fixed
        data:
          fixed-version: 1.4.1-r5

  - id: CGA-66vh-4j23-pfgm
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T07:38:48Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 45e5acba5c2bd1fa
            componentName: golang.org/x/crypto
            componentVersion: v0.32.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-03-11T15:42:42Z
        type: fixed
        data:
          fixed-version: 1.4.1-r4

  - id: CGA-7rwq-hhh8-jx92
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-09T10:03:07Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: cad369cb0b5a3d5b
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-02-10T00:29:56Z
        type: fixed
        data:
          fixed-version: 1.4.1-r2

  - id: CGA-8h5r-7866-vjvm
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T11:37:06Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: b73345e66ec97928
            componentName: golang.org/x/net
            componentVersion: v0.29.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2024-12-19T21:13:08Z
        type: fixed
        data:
          fixed-version: 1.4.0-r2

  - id: CGA-953j-8x4q-g3m9
    aliases:
      - CVE-2025-47907
      - GHSA-j5pm-7495-qmr3
    events:
      - timestamp: 2025-08-09T23:34:47Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: a40496e9c0157b6b
            componentName: stdlib
            componentVersion: go1.24.5
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-08-12T12:46:29Z
        type: fixed
        data:
          fixed-version: 1.4.2-r7

  - id: CGA-997x-72mw-vghp
    aliases:
      - CVE-2025-47914
      - GHSA-f6x5-jh6r-wrfv
    events:
      - timestamp: 2025-11-22T07:08:49Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 7d48652a6c814151
            componentName: golang.org/x/crypto
            componentVersion: v0.42.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-11-22T23:46:57Z
        type: fixed
        data:
          fixed-version: 1.5.1-r1

  - id: CGA-9mxv-p6rf-jmg2
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T11:42:32Z
        type: fixed
        data:
          fixed-version: 1.4.1-r1

  - id: CGA-cp56-w9wj-27f2
    aliases:
      - CVE-2025-22872
      - GHSA-vvgc-356p-c3xw
    events:
      - timestamp: 2025-04-17T10:27:26Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 30669d799fd1054d
            componentName: golang.org/x/net
            componentVersion: v0.36.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-04-19T05:25:44Z
        type: fixed
        data:
          fixed-version: 1.4.1-r42

  - id: CGA-fr26-4mr7-qqjr
    aliases:
      - CVE-2025-22874
      - GHSA-6f52-wpx2-hvf2
    events:
      - timestamp: 2025-06-15T06:12:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: c7a4e2fa3fde055c
            componentName: stdlib
            componentVersion: go1.24.3
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-06-15T12:18:38Z
        type: true-positive-determination
        data:
          note: 'Govulncheck found vulnerable symbols in Go binaries at the following locations: in nginx-prometheus-exporter-1.4.2-r1.apk, at usr/bin/nginx-prometheus-exporter, usr/bin/nginx-prometheus-exporter.'
      - timestamp: 2025-06-15T17:42:06Z
        type: fixed
        data:
          fixed-version: 1.4.2-r2

  - id: CGA-hcjw-8pmq-qm9r
    aliases:
      - CVE-2025-4673
      - GHSA-62jj-gr2r-5c34
    events:
      - timestamp: 2025-06-15T06:12:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: c7a4e2fa3fde055c
            componentName: stdlib
            componentVersion: go1.24.3
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-06-15T17:42:07Z
        type: fixed
        data:
          fixed-version: 1.4.2-r2

  - id: CGA-m566-8rw4-frjw
    aliases:
      - CVE-2025-22871
      - GHSA-g9pc-8g42-g6vq
    events:
      - timestamp: 2025-04-10T11:10:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: d7f673eb94ded28a
            componentName: stdlib
            componentVersion: go1.24.1
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-04-12T08:34:24Z
        type: fixed
        data:
          fixed-version: 1.4.1-r41

  - id: CGA-mg3q-333r-jj55
    aliases:
      - CVE-2025-47910
      - GHSA-8pjc-487g-w6p2
    events:
      - timestamp: 2025-09-24T10:09:28Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 49e227295a08ddd0
            componentName: stdlib
            componentVersion: go1.25.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-09-24T15:38:07Z
        type: fixed
        data:
          fixed-version: 1.5.0-r1

  - id: CGA-p785-xgxw-w4v8
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T07:38:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 6fb4912ebf11d8a5
            componentName: golang.org/x/oauth2
            componentVersion: v0.25.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2025-03-21T14:21:18Z
        type: fixed
        data:
          fixed-version: 1.4.1-r5

  - id: CGA-qmqm-5mv8-gr22
    aliases:
      - CVE-2025-58181
      - GHSA-j5w8-q4qc-rx2x
    events:
      - timestamp: 2025-11-22T07:08:50Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: 7d48652a6c814151
            componentName: golang.org/x/crypto
            componentVersion: v0.42.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype

  - id: CGA-r49f-8xpf-3gh9
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T10:12:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nginx-prometheus-exporter
            componentID: f609315be8dce324
            componentName: golang.org/x/crypto
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/nginx-prometheus-exporter
            scanner: grype
      - timestamp: 2024-12-12T17:19:04Z
        type: fixed
        data:
          fixed-version: 1.4.0-r1

  - id: CGA-vm5f-7j5x-2j4g
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T11:42:31Z
        type: fixed
        data:
          fixed-version: 1.4.1-r1
