schema-version: 2.0.2

package:
  name: nri-prometheus

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-16T18:52:16Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-16T18:53:14Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-16T18:54:05Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:34:52Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:34:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:18:34Z
        type: fixed
        data:
          fixed-version: 2.21.0-r3

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:18:23Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:18:24Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:18:21Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:18:21Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:18:22Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:19:43Z
        type: fixed
        data:
          fixed-version: 2.21.0-r2

  - id: CVE-2024-24787
    aliases:
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T10:31:57Z
        type: fixed
        data:
          fixed-version: 2.21.1-r1

  - id: CVE-2024-24788
    aliases:
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T10:31:59Z
        type: fixed
        data:
          fixed-version: 2.21.1-r1
