schema-version: 2.0.2

package:
  name: nri-prometheus

advisories:
  - id: CGA-2h5r-c628-cxhj
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T17:19:12Z
        type: fixed
        data:
          fixed-version: 2.21.3-r1

  - id: CGA-2mh9-c999-9c5q
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-11T00:29:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nri-prometheus
            componentID: 02e0778c7fdef969
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/nri-prometheus
            scanner: grype
      - timestamp: 2024-09-11T16:12:27Z
        type: fixed
        data:
          fixed-version: 2.21.5-r0

  - id: CGA-4334-6ppp-9wrj
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T10:31:59Z
        type: fixed
        data:
          fixed-version: 2.21.1-r1

  - id: CGA-4383-jmp4-2h28
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:19:43Z
        type: fixed
        data:
          fixed-version: 2.21.0-r2

  - id: CGA-4p4w-8h2x-v52q
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:34:52Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-5438-36j5-5wc8
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:18:23Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CGA-7w4j-qqj2-p6g7
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-11T00:29:17Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nri-prometheus
            componentID: 02e0778c7fdef969
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/nri-prometheus
            scanner: grype
      - timestamp: 2024-09-11T16:12:29Z
        type: fixed
        data:
          fixed-version: 2.21.5-r0

  - id: CGA-84qh-jmh2-fp4j
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T10:31:57Z
        type: fixed
        data:
          fixed-version: 2.21.1-r1

  - id: CGA-8jxq-q26h-mvgx
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T08:35:00Z
        type: fixed
        data:
          fixed-version: 2.23.1-r0

  - id: CGA-969m-cx5v-jrr6
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-16T18:53:14Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CGA-9r7r-h864-9jwx
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T09:33:09Z
        type: fixed
        data:
          fixed-version: 2.21.2-r1

  - id: CGA-fj32-q655-qwq3
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T08:35:45Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nri-prometheus
            componentID: bf474f8f9368fa52
            componentName: golang.org/x/net
            componentVersion: v0.26.0
            componentType: go-module
            componentLocation: /usr/bin/nri-prometheus
            scanner: grype
      - timestamp: 2024-12-19T13:30:33Z
        type: fixed
        data:
          fixed-version: 2.22.0-r2

  - id: CGA-fm4g-h5cv-pwcw
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:18:21Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CGA-gv86-rvw7-4f38
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-03-14T05:38:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nri-prometheus
            componentID: 3acd8de0e8c855e9
            componentName: golang.org/x/net
            componentVersion: v0.33.0
            componentType: go-module
            componentLocation: /usr/bin/nri-prometheus
            scanner: grype
      - timestamp: 2025-03-14T20:21:16Z
        type: fixed
        data:
          fixed-version: 2.24.1-r1

  - id: CGA-h9h2-fqfc-8pf7
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T11:43:38Z
        type: fixed
        data:
          fixed-version: 2.23.0-r1

  - id: CGA-hcmq-gmqw-788f
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:18:24Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CGA-mpwh-97pp-7gx7
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T09:33:05Z
        type: fixed
        data:
          fixed-version: 2.21.2-r1

  - id: CGA-pw46-7mxv-pv9h
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T18:18:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nri-prometheus
            componentID: d4a19f678e8a7571
            componentName: golang.org/x/oauth2
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/nri-prometheus
            scanner: grype
      - timestamp: 2025-03-21T21:10:06Z
        type: fixed
        data:
          fixed-version: 2.24.1-r1

  - id: CGA-r83c-wr9j-cf47
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-16T18:54:05Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CGA-rhv5-68w5-mmjc
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-11T00:29:12Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: nri-prometheus
            componentID: 02e0778c7fdef969
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/nri-prometheus
            scanner: grype
      - timestamp: 2024-09-11T16:12:28Z
        type: fixed
        data:
          fixed-version: 2.21.5-r0

  - id: CGA-rj4x-73jq-whmg
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-16T18:52:16Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CGA-rpmc-ggwq-j4vj
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:34:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-x5h5-hmmr-7282
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:18:34Z
        type: fixed
        data:
          fixed-version: 2.21.0-r3

  - id: CGA-x6q4-v9mj-m99q
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:18:22Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1

  - id: CGA-x8f3-xc2q-wv47
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T11:43:33Z
        type: fixed
        data:
          fixed-version: 2.23.0-r1

  - id: CGA-xhj2-wwx7-rv4v
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:18:21Z
        type: fixed
        data:
          fixed-version: 2.21.0-r1
