schema-version: 2.0.2

package:
  name: prometheus-adapter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:52:12Z
        type: fixed
        data:
          fixed-version: 0.11.1-r3

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:24Z
        type: fixed
        data:
          fixed-version: 0.11.1-r3

  - id: CVE-2023-44487
    aliases:
      - GHSA-m425-mq94-257g
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-11-06T23:30:58Z
        type: fixed
        data:
          fixed-version: 0.11.1-r4

  - id: CVE-2023-45142
    aliases:
      - GHSA-rcjv-mgp8-qvmr
    events:
      - timestamp: 2023-11-06T23:32:21Z
        type: fixed
        data:
          fixed-version: 0.11.1-r4

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:39Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:42Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:22:20Z
        type: fixed
        data:
          fixed-version: 0.11.2-r4

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:22:21Z
        type: fixed
        data:
          fixed-version: 0.11.2-r4

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-15T07:15:09Z
        type: fixed
        data:
          fixed-version: 0.11.2-r3

  - id: CVE-2023-5528
    aliases:
      - GHSA-hq6q-c2x6-hmch
    events:
      - timestamp: 2023-11-22T09:17:31Z
        type: fixed
        data:
          fixed-version: 0.11.2-r1
