schema-version: 2.0.2

package:
  name: prometheus-node-exporter

advisories:
  - id: CGA-2x8x-9778-3fm2
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T22:01:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-node-exporter
            componentID: f56e3f19fe9ae371
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/node_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:06:29Z
        type: fixed
        data:
          fixed-version: 1.8.2-r2

  - id: CGA-34gr-cf7g-pmh4
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T12:13:47Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-node-exporter
            componentID: a8aa190f96d5ab65
            componentName: golang.org/x/net
            componentVersion: v0.23.0
            componentType: go-module
            componentLocation: /usr/bin/node_exporter
            scanner: grype
      - timestamp: 2024-12-19T22:16:04Z
        type: fixed
        data:
          fixed-version: 1.8.2-r4

  - id: CGA-35m9-3xg4-vvq5
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:08Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-3f8p-v575-4v32
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T12:44:15Z
        type: fixed
        data:
          fixed-version: 1.8.1-r2

  - id: CGA-4jfw-w2fj-5jww
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:19:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CGA-4q76-9g98-7666
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T22:01:14Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-node-exporter
            componentID: f56e3f19fe9ae371
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/node_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:06:28Z
        type: fixed
        data:
          fixed-version: 1.8.2-r2

  - id: CGA-5w9h-cjpp-wwj5
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T10:12:49Z
        type: fixed
        data:
          fixed-version: 1.8.2-r5

  - id: CGA-745w-5238-qhq6
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T11:11:26Z
        type: fixed
        data:
          fixed-version: 1.8.1-r1

  - id: CGA-7h4h-5g3h-xf5f
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T11:43:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-node-exporter
            componentID: 53c63ad8c523dc82
            componentName: golang.org/x/crypto
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/node_exporter
            scanner: grype
      - timestamp: 2024-12-13T13:11:54Z
        type: fixed
        data:
          fixed-version: 1.8.2-r3

  - id: CGA-89c4-85h9-xh4w
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:19:29Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CGA-8c22-rh2f-cvgj
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-f68x-hw29-fjrw
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:19:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CGA-fpxv-vm5f-v5vj
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:19:30Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CGA-g253-pr98-4phg
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:16Z
        type: fixed
        data:
          fixed-version: 1.6.1-r6

  - id: CGA-g8f6-f8cr-cj3w
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T11:11:22Z
        type: fixed
        data:
          fixed-version: 1.8.1-r1

  - id: CGA-mmg6-c4j5-c72q
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:28:37Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-p29f-mff3-cf36
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:17:50Z
        type: fixed
        data:
          fixed-version: 1.7.0-r5

  - id: CGA-p953-jhwq-744w
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T22:01:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-node-exporter
            componentID: f56e3f19fe9ae371
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/node_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:06:28Z
        type: fixed
        data:
          fixed-version: 1.8.2-r2

  - id: CGA-pfv7-q59c-hx3w
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-31T01:45:49Z
        type: fixed
        data:
          fixed-version: 1.7.0-r4

  - id: CGA-pp2g-968v-623w
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:41Z
        type: fixed
        data:
          fixed-version: 1.6.1-r6

  - id: CGA-vxqh-38wc-3hxp
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:19:31Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CGA-x25f-2g6f-8m9w
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T10:12:43Z
        type: fixed
        data:
          fixed-version: 1.8.2-r5
