schema-version: 2.0.2

package:
  name: prometheus-3.3

advisories:
  - id: CGA-2895-ppv8-35hj
    aliases:
      - CVE-2025-22872
      - GHSA-vvgc-356p-c3xw
    events:
      - timestamp: 2025-04-30T21:49:14Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.3
            componentID: a1d1da031e93fed1
            componentName: golang.org/x/net
            componentVersion: v0.35.0
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2025-05-02T14:55:41Z
        type: fixed
        data:
          fixed-version: 3.3.0-r2

  - id: CGA-89xw-fcpm-98qx
    aliases:
      - CVE-2025-30204
      - GHSA-mh63-6h87-95cp
    events:
      - timestamp: 2025-04-30T21:49:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.3
            componentID: 48cd14a2794b75f1
            componentName: github.com/golang-jwt/jwt/v5
            componentVersion: v5.2.1
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype

  - id: CGA-rgxq-w398-3877
    aliases:
      - CVE-2025-22870
      - GHSA-qxp5-gwg8-xv66
    events:
      - timestamp: 2025-04-30T21:49:14Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.3
            componentID: a1d1da031e93fed1
            componentName: golang.org/x/net
            componentVersion: v0.35.0
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2025-05-02T14:55:42Z
        type: fixed
        data:
          fixed-version: 3.3.0-r2
