schema-version: 2.0.2

package:
  name: prometheus-bind-exporter

advisories:
  - id: CGA-2c54-93g6-r6gp
    aliases:
      - CVE-2023-39326
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-14T14:28:31Z
        type: fixed
        data:
          fixed-version: 0.7.0-r5

  - id: CGA-2wh6-g5j6-vgmw
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:17:25Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CGA-3pxq-44m8-vx6r
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T11:42:34Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 99693c32cf976dd1
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-11-06T14:13:27Z
        type: fixed
        data:
          fixed-version: 0.8.0-r0

  - id: CGA-3xjp-77xf-fhhc
    aliases:
      - CVE-2023-45285
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-14T14:28:32Z
        type: fixed
        data:
          fixed-version: 0.7.0-r5

  - id: CGA-55rm-5mvf-358q
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:17:23Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CGA-5834-95wq-988c
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-02-01T07:45:44Z
        type: fixed
        data:
          fixed-version: 0.8.0-r3

  - id: CGA-586x-8v37-ch77
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:17:20Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CGA-5p4w-9cg5-f227
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T21:03:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 92ed544c5aeaa3ce
            componentName: golang.org/x/crypto
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-12-13T15:18:05Z
        type: fixed
        data:
          fixed-version: 0.8.0-r1

  - id: CGA-6xjc-f67x-hxc6
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:49Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-7x46-gqpq-727w
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2024-02-14T14:31:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: eafd0a1834df4bcb
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CGA-8778-fhc9-mr54
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T11:42:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 99693c32cf976dd1
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-11-06T14:13:27Z
        type: fixed
        data:
          fixed-version: 0.8.0-r0

  - id: CGA-9xmc-qjr8-5m23
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2024-02-14T14:31:42Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: eafd0a1834df4bcb
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CGA-chm7-h279-7xfg
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T18:31:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 8fd885f48a4ec175
            componentName: golang.org/x/net
            componentVersion: v0.29.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-12-20T11:19:11Z
        type: fixed
        data:
          fixed-version: 0.8.0-r2

  - id: CGA-cm5m-v752-6385
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-09T02:29:52Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 9b379f1ac2d2941d
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2025-02-10T02:37:16Z
        type: fixed
        data:
          fixed-version: 0.8.0-r4

  - id: CGA-gppp-m374-7ww7
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T16:39:55Z
        type: fixed
        data:
          fixed-version: 0.7.0-r12

  - id: CGA-h7w7-g2pq-793q
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:47Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-jw3m-h94j-w7r2
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:19:59Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: e00a9fa3e2416fb6
            componentName: google.golang.org/protobuf
            componentVersion: v1.30.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-03-16T09:55:53Z
        type: fixed
        data:
          fixed-version: 0.7.0-r8

  - id: CGA-m68v-4rgg-74wg
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-02-01T07:45:51Z
        type: fixed
        data:
          fixed-version: 0.8.0-r3

  - id: CGA-mfw3-9p4f-353f
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T06:20:00Z
        type: fixed
        data:
          fixed-version: 0.7.0-r10

  - id: CGA-mqcw-h3xf-fr33
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T17:06:49Z
        type: fixed
        data:
          fixed-version: 0.7.0-r13

  - id: CGA-mw57-pmph-84gv
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T11:42:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 99693c32cf976dd1
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-11-06T14:13:26Z
        type: fixed
        data:
          fixed-version: 0.8.0-r0

  - id: CGA-pwcj-p254-rppg
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T12:37:18Z
        type: fixed
        data:
          fixed-version: 0.7.0-r11

  - id: CGA-qh9g-xvvc-5m58
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:17:21Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CGA-rf5r-mgp6-vj8r
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:17:22Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CGA-rqvh-82vx-5jcm
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:31:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 1ca9c3929639e2f3
            componentName: golang.org/x/crypto
            componentVersion: v0.8.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CGA-wx95-wrvj-5fxq
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2024-02-14T14:31:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: eafd0a1834df4bcb
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CGA-x2m8-phfw-47cx
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T12:37:20Z
        type: fixed
        data:
          fixed-version: 0.7.0-r11

  - id: CGA-xgff-63gq-jcpm
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T16:39:50Z
        type: fixed
        data:
          fixed-version: 0.7.0-r12
