schema-version: 2.0.2

package:
  name: prometheus-beat-exporter

advisories:
  - id: CGA-qfj2-h5hf-4mh5
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:21:34Z
        type: fixed
        data:
          fixed-version: 0.4.0-r3

  - id: CGA-pcqq-3229-j23c
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-h8c3-83mw-gxc2
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-qj69-j5v8-chww
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-6gwm-rp4v-fxmp
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T08:01:16Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-pcqr-p9mc-ppxr
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T08:01:16Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-p55p-42jq-vppv
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T16:37:21Z
        type: fixed
        data:
          fixed-version: 0.4.0-r2

  - id: CGA-52cc-v53x-475v
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:14:32Z
        type: fixed
        data:
          fixed-version: 0.4.0-r4

  - id: CGA-59cg-m3fg-x54g
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T13:14:33Z
        type: fixed
        data:
          fixed-version: 0.4.0-r4
