schema-version: 2.0.2

package:
  name: prometheus

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:54:43Z
        type: fixed
        data:
          fixed-version: 2.47.1-r3

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:58:22Z
        type: fixed
        data:
          fixed-version: 2.47.1-r3

  - id: CVE-2023-40577
    aliases:
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:46:25Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is an XSS flaw affecting alertmanager as a server not the library.

  - id: CVE-2023-44487
    aliases:
      - GHSA-m425-mq94-257g
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-11-06T22:06:07Z
        type: fixed
        data:
          fixed-version: 2.47.2-r4

  - id: CVE-2023-45142
    aliases:
      - GHSA-rcjv-mgp8-qvmr
    events:
      - timestamp: 2023-10-19T19:56:49Z
        type: fixed
        data:
          fixed-version: 2.47.2-r3

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:28Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:30Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45286
    aliases:
      - GHSA-xwh9-gc39-5298
    events:
      - timestamp: 2024-01-15T15:49:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus
            componentID: 3b942edfb590c552
            componentName: github.com/go-resty/resty/v2
            componentVersion: v2.10.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T09:38:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus
            componentID: b1b40d02ae289a8e
            componentName: stdlib
            componentVersion: go1.22.1
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:01:14Z
        type: fixed
        data:
          fixed-version: 2.50.1-r2

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T08:01:17Z
        type: fixed
        data:
          fixed-version: 2.50.1-r2

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2023-12-21T16:28:49Z
        type: fixed
        data:
          fixed-version: 2.48.1-r1

  - id: CVE-2024-24557
    aliases:
      - GHSA-xw73-rw38-6vjc
    events:
      - timestamp: 2024-03-21T11:42:58Z
        type: fixed
        data:
          fixed-version: 2.51.0-r1

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T08:01:18Z
        type: fixed
        data:
          fixed-version: 2.50.1-r2

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T08:01:16Z
        type: fixed
        data:
          fixed-version: 2.50.1-r2

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T08:01:20Z
        type: fixed
        data:
          fixed-version: 2.50.1-r2

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T11:16:31Z
        type: fixed
        data:
          fixed-version: 2.50.1-r3

  - id: CVE-2024-24787
    aliases:
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T07:19:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus
            componentID: b1b40d02ae289a8e
            componentName: stdlib
            componentVersion: go1.22.1
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CVE-2024-29018
    aliases:
      - GHSA-mq39-4gv4-mvpx
    events:
      - timestamp: 2024-03-21T11:43:15Z
        type: fixed
        data:
          fixed-version: 2.51.0-r1

  - id: GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2023-10-31T20:04:00Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is in the container runtime itself, not clients of the container runtime.
