schema-version: 2.0.2

package:
  name: prometheus-stackdriver-exporter

advisories:
  - id: CGA-227w-4c3j-9rq4
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-09T05:15:50Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 0a2d629a7a1da196
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2025-02-10T06:32:44Z
        type: fixed
        data:
          fixed-version: 0.18.0-r1

  - id: CGA-4wf5-cc6h-rcxw
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:29:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 3bd243bcbd49b349
            componentName: golang.org/x/crypto
            componentVersion: v0.8.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:28Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CGA-4xv8-7868-4wj4
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T20:16:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 4785551a9bdd31c5
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-09-19T11:35:27Z
        type: fixed
        data:
          fixed-version: 0.16.0-r1

  - id: CGA-72rv-77f5-42v9
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-05T09:11:36Z
        type: fixed
        data:
          fixed-version: 0.15.1-r2

  - id: CGA-g2g9-2296-9wpc
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:24Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-g436-hj79-37g5
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2024-02-14T14:29:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 68785c7367cc7b8b
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:28Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CGA-g8j7-jpmf-c33m
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T20:16:21Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 4785551a9bdd31c5
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-09-19T11:35:26Z
        type: fixed
        data:
          fixed-version: 0.16.0-r1

  - id: CGA-gj4c-crx2-pm8v
    aliases:
      - GHSA-m425-mq94-257g
    events:
      - timestamp: 2024-02-14T14:29:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: dbbbdfaffeed19a1
            componentName: google.golang.org/grpc
            componentVersion: v1.55.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:28Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CGA-h5m8-2j2p-g27r
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T09:21:55Z
        type: fixed
        data:
          fixed-version: 0.15.0-r0

  - id: CGA-hgcp-c6c6-8v5v
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T16:09:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 0893d95859cb2ba2
            componentName: golang.org/x/crypto
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-12-13T08:45:12Z
        type: fixed
        data:
          fixed-version: 0.17.0-r1

  - id: CGA-m2rg-gw8g-jq3g
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2024-02-14T14:29:40Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 68785c7367cc7b8b
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:29Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CGA-m67j-557q-99c6
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:17:38Z
        type: fixed
        data:
          fixed-version: 0.15.0-r1

  - id: CGA-p2rv-g632-r43m
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T14:01:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 72faaa3dce8cb4f9
            componentName: golang.org/x/net
            componentVersion: v0.30.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-12-20T01:17:20Z
        type: fixed
        data:
          fixed-version: 0.17.0-r2

  - id: CGA-p7v4-6cmg-g4w7
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T17:31:44Z
        type: fixed
        data:
          fixed-version: 0.15.1-r1

  - id: CGA-pmv4-q463-3j6w
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T13:09:03Z
        type: fixed
        data:
          fixed-version: 0.15.0-r3

  - id: CGA-pw4m-2xrm-7q54
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:22Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-qpf8-6m86-7q84
    aliases:
      - CVE-2023-45285
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-17T07:42:26Z
        type: fixed
        data:
          fixed-version: 0.14.1-r7

  - id: CGA-r9qq-3r2c-h7g5
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2024-02-14T14:29:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 68785c7367cc7b8b
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:29Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CGA-vj8x-gx7g-g3rj
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:09:01Z
        type: fixed
        data:
          fixed-version: 0.15.0-r3

  - id: CGA-vxjg-f47q-5469
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T20:16:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 4785551a9bdd31c5
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-09-19T11:35:27Z
        type: fixed
        data:
          fixed-version: 0.16.0-r1

  - id: CGA-w47p-hhcc-9323
    aliases:
      - CVE-2023-39326
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-17T07:42:24Z
        type: fixed
        data:
          fixed-version: 0.14.1-r7

  - id: CGA-wvrf-c4p7-vg52
    aliases:
      - CVE-2022-41723
      - GHSA-vvpx-j8f3-3w6h
    events:
      - timestamp: 2023-05-02T22:52:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used

  - id: CGA-x67p-x4ph-9wjr
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T17:31:41Z
        type: fixed
        data:
          fixed-version: 0.15.1-r1
