schema-version: 2.0.2

package:
  name: prometheus-node-exporter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:41Z
        type: fixed
        data:
          fixed-version: 1.6.1-r6

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:16Z
        type: fixed
        data:
          fixed-version: 1.6.1-r6

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:08Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:17:50Z
        type: fixed
        data:
          fixed-version: 1.7.0-r5

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:19:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:19:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:28:37Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:19:29Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:19:30Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:19:31Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-31T01:45:49Z
        type: fixed
        data:
          fixed-version: 1.7.0-r4
