schema-version: 2.0.2

package:
  name: prometheus-2.52

advisories:
  - id: CGA-25v6-p39j-f3qj
    aliases:
      - CVE-2024-36620
      - GHSA-q59j-vv4j-v33c
    events:
      - timestamp: 2025-03-06T02:44:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 779fbbee3340a363
            componentName: github.com/docker/docker
            componentVersion: v26.0.2+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-38pv-q942-mc4q
    aliases:
      - CVE-2024-6104
      - GHSA-v6v8-xj6m-xwqh
    events:
      - timestamp: 2025-03-06T02:44:13Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: b24ab4745a22c4da
            componentName: github.com/hashicorp/go-retryablehttp
            componentVersion: v0.7.4
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-399w-6v3v-h4j2
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T02:44:18Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 715af6c8c05cfdae
            componentName: golang.org/x/crypto
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-7ww8-4mj4-j34q
    aliases:
      - CVE-2024-32473
      - GHSA-x84c-p2g9-rqv9
    events:
      - timestamp: 2024-05-13T17:13:44Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: c742fa339928efa2
            componentName: github.com/docker/docker
            componentVersion: v26.0.1+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-05-13T18:00:54Z
        type: fixed
        data:
          fixed-version: 2.52.0-r1

  - id: CGA-8c5w-6qc6-rrpf
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2025-03-06T02:44:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 715af6c8c05cfdae
            componentName: golang.org/x/crypto
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-9ffx-48cq-jpwr
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2025-03-06T02:44:21Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 3967a42dc5699527
            componentName: stdlib
            componentVersion: go1.22.4
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-g4p9-9qwx-r3c3
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T02:44:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 487ebb7c98e91080
            componentName: golang.org/x/oauth2
            componentVersion: v0.19.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-j523-px72-wj4f
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2025-03-06T02:44:24Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 3967a42dc5699527
            componentName: stdlib
            componentVersion: go1.22.4
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-j955-q78q-ff9q
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2025-03-06T02:44:06Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 779fbbee3340a363
            componentName: github.com/docker/docker
            componentVersion: v26.0.2+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-m2gp-5544-qvw3
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T20:05:46Z
        type: fixed
        data:
          fixed-version: 2.52.0-r3

  - id: CGA-p8jg-97p2-4jhc
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T20:05:45Z
        type: fixed
        data:
          fixed-version: 2.52.0-r3

  - id: CGA-wj6j-g9jc-cm4q
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-03-06T02:44:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: b0a0f3bbf8eb7de2
            componentName: golang.org/x/net
            componentVersion: v0.26.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-x6c3-p37f-phhf
    aliases:
      - CVE-2024-35255
      - GHSA-m5vv-6r4h-3vj9
    events:
      - timestamp: 2024-06-12T09:30:54Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 5bfca14eb757b3d7
            componentName: github.com/Azure/azure-sdk-for-go/sdk/azidentity
            componentVersion: v1.5.2
            componentType: go-module
            componentLocation: /usr/bin/promtool
            scanner: grype
      - timestamp: 2024-06-12T12:34:53Z
        type: fixed
        data:
          fixed-version: 2.52.0-r4
