schema-version: 2.0.2

package:
  name: prometheus-operator

advisories:
  - id: CVE-2019-3826
    aliases:
      - GHSA-3m87-5598-2v4f
    events:
      - timestamp: 2023-08-11T21:13:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used
          note: This CVE only impacts prometheus 2.7 but our prometheus-operator is using v0.46.0 Go library which is in fact prothemeus 2.46

  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:53Z
        type: fixed
        data:
          fixed-version: 0.68.0-r4

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:31Z
        type: fixed
        data:
          fixed-version: 0.68.0-r4

  - id: CVE-2023-40577
    aliases:
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:47:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is an XSS flaw affecting alertmanager as a server, not when imported as a library.

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:10Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:11Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-20T17:26:55Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 2f35106dda8550a0
            componentName: golang.org/x/net
            componentVersion: v0.22.0
            componentType: go-module
            componentLocation: /usr/bin/operator
            scanner: grype

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:19:12Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:19:13Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:19:14Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:19:10Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:19:11Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:18:51Z
        type: fixed
        data:
          fixed-version: 0.72.0-r2
