schema-version: 2.0.2

package:
  name: prometheus-mysqld-exporter

advisories:
  - id: CGA-372h-96r9-v9ff
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:19:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 89d3a797853f608f
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-03-31T01:37:49Z
        type: fixed
        data:
          fixed-version: 0.15.1-r4

  - id: CGA-3hfr-25xf-qc4f
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T10:02:59Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CGA-4fw9-mm7r-h39f
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T07:19:18Z
        type: fixed
        data:
          fixed-version: 0.15.1-r8

  - id: CGA-4r86-767f-hm58
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T12:34:02Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: ee56b8aad8687dc3
            componentName: golang.org/x/crypto
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-12-13T11:16:24Z
        type: fixed
        data:
          fixed-version: 0.16.0-r1

  - id: CGA-5gph-frf3-j4cg
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T10:02:57Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CGA-5jcj-8v3w-qhxh
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T18:07:34Z
        type: fixed
        data:
          fixed-version: 0.16.0-r3

  - id: CGA-7wqh-h75j-fw57
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T13:32:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 73eecbf04d576819
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-09-12T21:05:22Z
        type: fixed
        data:
          fixed-version: 0.15.1-r10

  - id: CGA-87pv-v73v-vw26
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T11:01:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 26e4faaf951e64c3
            componentName: golang.org/x/net
            componentVersion: v0.17.0
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-05-02T17:15:29Z
        type: fixed
        data:
          fixed-version: 0.15.1-r6

  - id: CGA-8hqp-vrrv-526w
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-15T13:12:40Z
        type: fixed
        data:
          fixed-version: 0.15.1-r7

  - id: CGA-94jw-g7w5-h2gx
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T16:20:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: cafa380de7a946db
            componentName: golang.org/x/net
            componentVersion: v0.29.0
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-12-20T06:45:21Z
        type: fixed
        data:
          fixed-version: 0.16.0-r2

  - id: CGA-9qg7-qfhw-8gj5
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T18:07:28Z
        type: fixed
        data:
          fixed-version: 0.16.0-r3

  - id: CGA-cfgr-vm64-rjxc
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T17:18:07Z
        type: fixed
        data:
          fixed-version: 0.15.1-r9

  - id: CGA-fh84-w5vf-qjmc
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T10:02:56Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CGA-fq3r-fjj5-cf72
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-01-27T07:11:14Z
        type: fixed
        data:
          fixed-version: 0.15.1-r2

  - id: CGA-g8fx-h4gr-62ch
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:29Z
        type: fixed
        data:
          fixed-version: 0.15.0-r6

  - id: CGA-gpgx-9px7-mr38
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:00Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-hq9v-c379-hv9v
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:06Z
        type: fixed
        data:
          fixed-version: 0.15.0-r6

  - id: CGA-j78j-5v8q-mm38
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T07:19:21Z
        type: fixed
        data:
          fixed-version: 0.15.1-r8

  - id: CGA-pv2w-fww6-ph69
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T10:02:58Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CGA-q75q-28xp-47qv
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T10:02:56Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CGA-rrvc-vh4c-m8cp
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T13:32:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 73eecbf04d576819
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-09-12T21:05:21Z
        type: fixed
        data:
          fixed-version: 0.15.1-r10

  - id: CGA-wf66-4qvp-vj6j
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-15T13:12:38Z
        type: fixed
        data:
          fixed-version: 0.15.1-r7

  - id: CGA-wjw5-9x5q-gwpf
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:02Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-xr5q-2xpm-pm8q
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T13:32:09Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 73eecbf04d576819
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-09-12T21:05:22Z
        type: fixed
        data:
          fixed-version: 0.15.1-r10
