schema-version: 2.0.2

package:
  name: prometheus-2.52

advisories:
  - id: CGA-25v6-p39j-f3qj
    aliases:
      - CVE-2024-36620
      - GHSA-q59j-vv4j-v33c
    events:
      - timestamp: 2025-03-06T02:44:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 779fbbee3340a363
            componentName: github.com/docker/docker
            componentVersion: v26.0.2+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-7ww8-4mj4-j34q
    aliases:
      - CVE-2024-32473
      - GHSA-x84c-p2g9-rqv9
    events:
      - timestamp: 2024-05-13T17:13:44Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: c742fa339928efa2
            componentName: github.com/docker/docker
            componentVersion: v26.0.1+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-05-13T18:00:54Z
        type: fixed
        data:
          fixed-version: 2.52.0-r1

  - id: CGA-m2gp-5544-qvw3
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T20:05:46Z
        type: fixed
        data:
          fixed-version: 2.52.0-r3

  - id: CGA-p8jg-97p2-4jhc
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T20:05:45Z
        type: fixed
        data:
          fixed-version: 2.52.0-r3

  - id: CGA-x6c3-p37f-phhf
    aliases:
      - CVE-2024-35255
      - GHSA-m5vv-6r4h-3vj9
    events:
      - timestamp: 2024-06-12T09:30:54Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.52
            componentID: 5bfca14eb757b3d7
            componentName: github.com/Azure/azure-sdk-for-go/sdk/azidentity
            componentVersion: v1.5.2
            componentType: go-module
            componentLocation: /usr/bin/promtool
            scanner: grype
      - timestamp: 2024-06-12T12:34:53Z
        type: fixed
        data:
          fixed-version: 2.52.0-r4
