schema-version: 2.0.2

package:
  name: prometheus-beat-exporter

advisories:
  - id: CGA-27gc-c3gm-f839
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T14:42:07Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-beat-exporter
            componentID: 28aaa0d3a8c082fc
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/beat-exporter
            scanner: grype
      - timestamp: 2024-09-18T20:23:30Z
        type: fixed
        data:
          fixed-version: 0.4.0-r7

  - id: CGA-33qh-63q7-p56q
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T19:18:42Z
        type: fixed
        data:
          fixed-version: 0.4.0-r5

  - id: CGA-52cc-v53x-475v
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:14:32Z
        type: fixed
        data:
          fixed-version: 0.4.0-r4

  - id: CGA-59cg-m3fg-x54g
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T13:14:33Z
        type: fixed
        data:
          fixed-version: 0.4.0-r4

  - id: CGA-6gg9-vwj4-77wv
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T19:18:44Z
        type: fixed
        data:
          fixed-version: 0.4.0-r5

  - id: CGA-6gwm-rp4v-fxmp
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T08:01:16Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-6mqr-c63c-7pwr
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T14:41:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-beat-exporter
            componentID: 28aaa0d3a8c082fc
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/beat-exporter
            scanner: grype
      - timestamp: 2024-09-18T20:23:29Z
        type: fixed
        data:
          fixed-version: 0.4.0-r7

  - id: CGA-h8c3-83mw-gxc2
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-p55p-42jq-vppv
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T16:37:21Z
        type: fixed
        data:
          fixed-version: 0.4.0-r2

  - id: CGA-pcqq-3229-j23c
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-pcqr-p9mc-ppxr
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T08:01:16Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-q7f4-375j-qh7m
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T11:09:43Z
        type: fixed
        data:
          fixed-version: 0.4.0-r8

  - id: CGA-qfj2-h5hf-4mh5
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:21:34Z
        type: fixed
        data:
          fixed-version: 0.4.0-r3

  - id: CGA-qj69-j5v8-chww
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1

  - id: CGA-rwmq-7xqp-3r9w
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T07:31:03Z
        type: fixed
        data:
          fixed-version: 0.4.0-r6

  - id: CGA-vgw7-m2q4-whpp
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T14:41:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-beat-exporter
            componentID: 28aaa0d3a8c082fc
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/beat-exporter
            scanner: grype
      - timestamp: 2024-09-18T20:23:29Z
        type: fixed
        data:
          fixed-version: 0.4.0-r7
