schema-version: 2.0.2

package:
  name: prometheus-bind-exporter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2024-02-14T14:31:42Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: eafd0a1834df4bcb
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CVE-2023-39326
    aliases:
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-14T14:28:31Z
        type: fixed
        data:
          fixed-version: 0.7.0-r5

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2024-02-14T14:31:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: eafd0a1834df4bcb
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2024-02-14T14:31:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: eafd0a1834df4bcb
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:47Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:49Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45285
    aliases:
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-14T14:28:32Z
        type: fixed
        data:
          fixed-version: 0.7.0-r5

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T06:20:00Z
        type: fixed
        data:
          fixed-version: 0.7.0-r10

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:17:21Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:17:22Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:31:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: 1ca9c3929639e2f3
            componentName: golang.org/x/crypto
            componentVersion: v0.8.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-02-14T19:30:29Z
        type: fixed
        data:
          fixed-version: 0.7.0-r6

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:17:23Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:17:25Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:17:20Z
        type: fixed
        data:
          fixed-version: 0.7.0-r7

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:19:59Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-bind-exporter
            componentID: e00a9fa3e2416fb6
            componentName: google.golang.org/protobuf
            componentVersion: v1.30.0
            componentType: go-module
            componentLocation: /usr/bin/bind_exporter
            scanner: grype
      - timestamp: 2024-03-16T09:55:53Z
        type: fixed
        data:
          fixed-version: 0.7.0-r8

  - id: CVE-2024-24787
    aliases:
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T12:37:18Z
        type: fixed
        data:
          fixed-version: 0.7.0-r11
