schema-version: 2.0.2

package:
  name: prometheus-2.53

advisories:
  - id: CGA-2r4p-9jq9-gc3r
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2024-07-31T10:35:28Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.53
            componentID: 593a1baab7503325
            componentName: github.com/docker/docker
            componentVersion: v26.1.3+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-07-31T16:21:19Z
        type: fixed
        data:
          fixed-version: 2.53.1-r1

  - id: CGA-42xw-m687-xw7w
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T10:03:43Z
        type: fixed
        data:
          fixed-version: 2.53.0-r3

  - id: CGA-cf4m-fxmm-hxv2
    aliases:
      - GHSA-xr7q-jx4m-x55m
    events:
      - timestamp: 2024-07-10T07:31:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.53
            componentID: 478fda29853e77b7
            componentName: google.golang.org/grpc
            componentVersion: v1.64.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-07-10T11:14:04Z
        type: fixed
        data:
          fixed-version: 2.53.0-r4

  - id: CGA-ch4c-vjfp-7v53
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2025-03-06T03:02:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.53
            componentID: f2bcd41f95f098a5
            componentName: golang.org/x/crypto
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-vr63-h43x-c39j
    aliases:
      - CVE-2024-6104
      - GHSA-v6v8-xj6m-xwqh
    events:
      - timestamp: 2024-06-25T08:06:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.53
            componentID: b24ab4745a22c4da
            componentName: github.com/hashicorp/go-retryablehttp
            componentVersion: v0.7.4
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-06-25T10:31:41Z
        type: fixed
        data:
          fixed-version: 2.53.0-r2
