schema-version: 2.0.2

package:
  name: prometheus-operator

advisories:
  - id: CGA-2j8x-4qrp-whj7
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:19:10Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-2m37-ffx6-c3pr
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:10Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-2v76-f4w2-7j44
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:18:51Z
        type: fixed
        data:
          fixed-version: 0.72.0-r2

  - id: CGA-38jv-r2vm-cm37
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T07:40:52Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 5a0b7dfb162ccef7
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/operator
            scanner: grype
      - timestamp: 2025-02-08T10:43:28Z
        type: fixed
        data:
          fixed-version: 0.80.0-r1

  - id: CGA-3x9p-grpv-c654
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:19:13Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-4cmq-3qw8-c33m
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T11:02:44Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 485d0eafe4ec3d7d
            componentName: golang.org/x/crypto
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-config-reloader
            scanner: grype
      - timestamp: 2024-12-12T20:21:37Z
        type: fixed
        data:
          fixed-version: 0.78.2-r1

  - id: CGA-68g9-hch7-5grp
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T14:22:36Z
        type: fixed
        data:
          fixed-version: 0.74.0-r1

  - id: CGA-6rmv-w7pm-p5vm
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:19:12Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-7f4h-m585-rhrp
    aliases:
      - CVE-2023-40577
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:47:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is an XSS flaw affecting alertmanager as a server, not when imported as a library.

  - id: CGA-7p3m-xjr2-wx24
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-02-01T16:45:46Z
        type: fixed
        data:
          fixed-version: 0.79.2-r2

  - id: CGA-88wx-wcc3-r89v
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:53Z
        type: fixed
        data:
          fixed-version: 0.68.0-r4

  - id: CGA-96hr-8566-xc9j
    aliases:
      - CVE-2024-35255
      - GHSA-m5vv-6r4h-3vj9
    events:
      - timestamp: 2024-06-12T09:23:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 66618b18d7a36623
            componentName: github.com/Azure/azure-sdk-for-go/sdk/azidentity
            componentVersion: v1.5.2
            componentType: go-module
            componentLocation: /usr/bin/operator
            scanner: grype
      - timestamp: 2024-06-12T12:00:35Z
        type: fixed
        data:
          fixed-version: 0.74.0-r2

  - id: CGA-9j3c-22fm-27qx
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T19:41:21Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 2575801c6ad80299
            componentName: golang.org/x/net
            componentVersion: v0.32.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-config-reloader
            scanner: grype
      - timestamp: 2024-12-20T15:14:00Z
        type: fixed
        data:
          fixed-version: 0.79.2-r1

  - id: CGA-cwwx-38rj-4mfh
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:11Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-f7jj-h729-p7ww
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T07:11:59Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-admission-webhook
            componentID: e7ec4d0c6fe16b9c
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/admission-webhook
            scanner: grype
      - timestamp: 2025-03-20T19:39:13Z
        type: fixed
        data:
          fixed-version: 0.81.0-r1

  - id: CGA-jx34-6h53-cg55
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:19:11Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-jxcg-5j7g-6w5w
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-20T17:26:55Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 2f35106dda8550a0
            componentName: golang.org/x/net
            componentVersion: v0.22.0
            componentType: go-module
            componentLocation: /usr/bin/operator
            scanner: grype
      - timestamp: 2024-04-23T17:14:32Z
        type: fixed
        data:
          fixed-version: 0.73.2-r1

  - id: CGA-jxjf-j63h-3jpv
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:19:14Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-m4v2-64jf-4976
    aliases:
      - CVE-2019-3826
      - GHSA-3m87-5598-2v4f
    events:
      - timestamp: 2023-08-11T21:13:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used
          note: This CVE only impacts prometheus 2.7 but our prometheus-operator is using v0.46.0 Go library which is in fact prothemeus 2.46
      - timestamp: 2025-03-04T18:02:01Z
        type: false-positive-determination
        data:
          type: component-vulnerability-mismatch
          note: Prometheus ships a Go (Golang) library with a versioning scheme that follows the 0.x format. However, the Prometheus application itself uses a versioning scheme based on 1.x, 2.x, etc. The vulnerability identified in CVE-2019-3826 is specifically associated with the Prometheus application, not the Golang library.

  - id: CGA-p2c9-fmw8-fhrq
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T07:12:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-admission-webhook
            componentID: e7ec4d0c6fe16b9c
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/admission-webhook
            scanner: grype
      - timestamp: 2025-03-20T19:39:14Z
        type: fixed
        data:
          fixed-version: 0.81.0-r1

  - id: CGA-p89g-55q3-r3r8
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-11T15:01:26Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: acc38c5ef138bddc
            componentName: golang.org/x/crypto
            componentVersion: v0.32.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-config-reloader
            scanner: grype
      - timestamp: 2025-03-11T17:01:42Z
        type: fixed
        data:
          fixed-version: 0.81.0-r0

  - id: CGA-p9mx-qhcq-pcfr
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-11T15:01:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: a6a9801f96dcd003
            componentName: golang.org/x/oauth2
            componentVersion: v0.25.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-config-reloader
            scanner: grype
      - timestamp: 2025-03-12T23:20:00Z
        type: fixed
        data:
          fixed-version: 0.81.0-r1

  - id: CGA-qwjx-9h4v-57mw
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T07:11:55Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-admission-webhook
            componentID: e7ec4d0c6fe16b9c
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/admission-webhook
            scanner: grype
      - timestamp: 2025-03-20T19:39:14Z
        type: fixed
        data:
          fixed-version: 0.81.0-r1

  - id: CGA-r8cw-v96g-jwpv
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T14:22:32Z
        type: fixed
        data:
          fixed-version: 0.74.0-r1

  - id: CGA-rgwm-cw32-rh3f
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-02-01T16:45:41Z
        type: fixed
        data:
          fixed-version: 0.79.2-r2

  - id: CGA-vxp3-vwx2-gqw6
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:31Z
        type: fixed
        data:
          fixed-version: 0.68.0-r4
