schema-version: 2.0.2

package:
  name: prometheus-statsd-exporter

advisories:
  - id: CGA-2935-r8j6-3f9h
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T11:09:30Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: 5f92c394993485ae
            componentName: golang.org/x/net
            componentVersion: v0.20.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-05-02T17:17:15Z
        type: fixed
        data:
          fixed-version: 0.26.1-r2

  - id: CGA-29fm-776f-638j
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T18:37:09Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: 670595bdb793e4f5
            componentName: golang.org/x/crypto
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-12-13T11:44:31Z
        type: fixed
        data:
          fixed-version: 0.28.0-r1

  - id: CGA-2jgg-m4pg-728h
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-15T07:21:44Z
        type: fixed
        data:
          fixed-version: 0.26.0-r1

  - id: CGA-599x-xf5m-jxjj
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:58:10Z
        type: fixed
        data:
          fixed-version: 0.24.0-r3

  - id: CGA-5f9h-gp7q-rq99
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T10:03:20Z
        type: fixed
        data:
          fixed-version: 0.26.0-r2

  - id: CGA-6ggm-4xph-7p34
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T10:14:48Z
        type: fixed
        data:
          fixed-version: 0.26.1-r3

  - id: CGA-7268-7fg8-jwpx
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T11:11:10Z
        type: fixed
        data:
          fixed-version: 0.26.1-r5

  - id: CGA-8fww-7wxj-4j6x
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T08:34:54Z
        type: fixed
        data:
          fixed-version: 0.26.1-r4

  - id: CGA-8xjj-w2p7-rvjw
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T08:34:57Z
        type: fixed
        data:
          fixed-version: 0.26.1-r4

  - id: CGA-9573-wqj2-mff7
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T10:03:19Z
        type: fixed
        data:
          fixed-version: 0.26.0-r2

  - id: CGA-97cr-hv8p-6w76
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-02-01T19:22:55Z
        type: fixed
        data:
          fixed-version: 0.28.0-r3

  - id: CGA-9847-fwxc-x8hc
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T16:39:33Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: a745b236fa352365
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-09-13T11:01:32Z
        type: fixed
        data:
          fixed-version: 0.27.1-r2

  - id: CGA-9964-j5g2-mmq9
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T10:03:17Z
        type: fixed
        data:
          fixed-version: 0.26.0-r2

  - id: CGA-c7v4-vx49-frpp
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:25Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-g55j-5jp9-5fv7
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T10:03:18Z
        type: fixed
        data:
          fixed-version: 0.26.0-r2

  - id: CGA-gh36-5pfj-m5gf
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T21:15:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: 6a291323b1710b9d
            componentName: golang.org/x/net
            componentVersion: v0.29.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-12-20T16:26:18Z
        type: fixed
        data:
          fixed-version: 0.28.0-r2

  - id: CGA-hww2-h7j7-5hcf
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T10:03:17Z
        type: fixed
        data:
          fixed-version: 0.26.0-r2

  - id: CGA-hxg2-grmg-j3r2
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:27Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-hxpr-35cr-g7h2
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T16:39:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: a745b236fa352365
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-09-13T11:01:33Z
        type: fixed
        data:
          fixed-version: 0.27.1-r2

  - id: CGA-j3h5-4qw2-26mq
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T16:39:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: a745b236fa352365
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-09-13T11:01:32Z
        type: fixed
        data:
          fixed-version: 0.27.1-r2

  - id: CGA-jqf7-m9wx-ppvm
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:54:30Z
        type: fixed
        data:
          fixed-version: 0.24.0-r3

  - id: CGA-q9hj-2cr5-xx66
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T10:14:50Z
        type: fixed
        data:
          fixed-version: 0.26.1-r3

  - id: CGA-r92x-qjfr-jx29
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-02-01T19:22:49Z
        type: fixed
        data:
          fixed-version: 0.28.0-r3

  - id: CGA-xjh5-h33v-5mx3
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:19:42Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-statsd-exporter
            componentID: afd3852cfc7f252e
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/statsd_exporter
            scanner: grype
      - timestamp: 2024-03-16T11:02:27Z
        type: fixed
        data:
          fixed-version: 0.26.0-r3
