schema-version: 2.0.2

package:
  name: prometheus-2.51

advisories:
  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:20:04Z
        type: fixed
        data:
          fixed-version: 2.51.1-r1

  - id: CVE-2024-29018
    aliases:
      - GHSA-mq39-4gv4-mvpx
    events:
      - timestamp: 2024-03-22T13:57:44Z
        type: fixed
        data:
          fixed-version: 2.51.0-r1
