schema-version: 2.0.2

package:
  name: prometheus-redis-exporter

advisories:
  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:19Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:21Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:27:41Z
        type: fixed
        data:
          fixed-version: 1.58.0-r3

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T07:10:51Z
        type: fixed
        data:
          fixed-version: 1.58.0-r1

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-13T07:10:51Z
        type: fixed
        data:
          fixed-version: 1.58.0-r1

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-13T07:10:52Z
        type: fixed
        data:
          fixed-version: 1.58.0-r1

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T07:10:52Z
        type: fixed
        data:
          fixed-version: 1.58.0-r1

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T07:10:50Z
        type: fixed
        data:
          fixed-version: 1.58.0-r1

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:20:55Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-redis-exporter
            componentID: c4ea2bb877e96704
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/redis_exporter
            scanner: grype
      - timestamp: 2024-03-31T01:30:34Z
        type: fixed
        data:
          fixed-version: 1.58.0-r2
