schema-version: 2.0.2

package:
  name: prometheus-3.7

advisories:
  - id: CGA-9vg2-cg26-8gg9
    aliases:
      - CVE-2025-47914
      - GHSA-f6x5-jh6r-wrfv
    events:
      - timestamp: 2025-11-22T20:17:31Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.7
            componentID: b3498b988dec8a8d
            componentName: golang.org/x/crypto
            componentVersion: v0.42.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
