schema-version: 2.0.2

package:
  name: prometheus-3.1

advisories:
  - id: CGA-2fwf-p7c9-3xmf
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T10:16:50Z
        type: fixed
        data:
          fixed-version: 3.1.0-r3

  - id: CGA-pgx9-6xff-jgfj
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-01-05T10:34:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.1
            componentID: e7a1c8dc47b22d91
            componentName: golang.org/x/net
            componentVersion: v0.32.0
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2025-01-05T20:01:37Z
        type: fixed
        data:
          fixed-version: 3.1.0-r2
