schema-version: 2.0.2

package:
  name: prometheus-elasticsearch-exporter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:02Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:31Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:47Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:16Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-18T03:55:41Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T10:18:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: ff69c4097c2c475c
            componentName: golang.org/x/net
            componentVersion: v0.17.0
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T07:13:26Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-13T07:13:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-13T07:13:28Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T07:13:25Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T07:13:26Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-16T11:02:03Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3
