schema-version: 2.0.2

package:
  name: prometheus-alertmanager

advisories:
  - id: CGA-22g9-qfxx-mx6h
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:37Z
        type: fixed
        data:
          fixed-version: 0.26.0-r4

  - id: CGA-22w3-mqjp-67qc
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:18:12Z
        type: fixed
        data:
          fixed-version: 0.27.0-r1

  - id: CGA-292h-qwj8-wm75
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:18:11Z
        type: fixed
        data:
          fixed-version: 0.27.0-r1

  - id: CGA-32p3-85r5-h676
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:52:53Z
        type: fixed
        data:
          fixed-version: 0.26.0-r4

  - id: CGA-57v6-x9px-rcg2
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:28:36Z
        type: fixed
        data:
          fixed-version: 0.26.0-r6

  - id: CGA-59q3-6xjj-5wgw
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:19:32Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-alertmanager
            componentID: 135ecbf9a6001eb0
            componentName: google.golang.org/protobuf
            componentVersion: v1.32.0
            componentType: go-module
            componentLocation: /usr/bin/alertmanager
            scanner: grype
      - timestamp: 2024-03-17T14:49:36Z
        type: fixed
        data:
          fixed-version: 0.27.0-r2

  - id: CGA-cp98-m225-5r8c
    aliases:
      - CVE-2023-40577
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:39:59Z
        type: fixed
        data:
          fixed-version: 0.26.0-r0

  - id: CGA-cwf3-5p6r-h729
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-10T09:11:35Z
        type: fixed
        data:
          fixed-version: 0.27.0-r3

  - id: CGA-frc6-7v2f-j768
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:44Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-fx49-467m-pc3q
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:18:13Z
        type: fixed
        data:
          fixed-version: 0.27.0-r1

  - id: CGA-hx3h-4xvx-pg6h
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T07:18:15Z
        type: fixed
        data:
          fixed-version: 0.27.0-r6

  - id: CGA-jw36-2779-24rq
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T11:18:11Z
        type: fixed
        data:
          fixed-version: 0.27.0-r5

  - id: CGA-m678-xqwm-fcw4
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:46Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-mppq-g3f5-wp3m
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:18:14Z
        type: fixed
        data:
          fixed-version: 0.27.0-r1

  - id: CGA-qwhp-882g-xv83
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:18:10Z
        type: fixed
        data:
          fixed-version: 0.27.0-r1

  - id: CGA-rr7g-wfr5-p444
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T11:18:13Z
        type: fixed
        data:
          fixed-version: 0.27.0-r5
