schema-version: 2.0.2

package:
  name: prometheus-operator

advisories:
  - id: CGA-m4v2-64jf-4976
    aliases:
      - CVE-2019-3826
      - GHSA-3m87-5598-2v4f
    events:
      - timestamp: 2023-08-11T21:13:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used
          note: This CVE only impacts prometheus 2.7 but our prometheus-operator is using v0.46.0 Go library which is in fact prothemeus 2.46

  - id: CGA-88wx-wcc3-r89v
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:53Z
        type: fixed
        data:
          fixed-version: 0.68.0-r4

  - id: CGA-vxp3-vwx2-gqw6
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:31Z
        type: fixed
        data:
          fixed-version: 0.68.0-r4

  - id: CGA-7f4h-m585-rhrp
    aliases:
      - CVE-2023-40577
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:47:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is an XSS flaw affecting alertmanager as a server, not when imported as a library.

  - id: CGA-2m37-ffx6-c3pr
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:10Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-cwwx-38rj-4mfh
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:11Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-jxcg-5j7g-6w5w
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-20T17:26:55Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-operator
            componentID: 2f35106dda8550a0
            componentName: golang.org/x/net
            componentVersion: v0.22.0
            componentType: go-module
            componentLocation: /usr/bin/operator
            scanner: grype
      - timestamp: 2024-04-23T17:14:32Z
        type: fixed
        data:
          fixed-version: 0.73.2-r1

  - id: CGA-6rmv-w7pm-p5vm
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:19:12Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-3x9p-grpv-c654
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:19:13Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-jxjf-j63h-3jpv
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:19:14Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-2j8x-4qrp-whj7
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:19:10Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-jx34-6h53-cg55
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:19:11Z
        type: fixed
        data:
          fixed-version: 0.72.0-r1

  - id: CGA-2v76-f4w2-7j44
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T15:18:51Z
        type: fixed
        data:
          fixed-version: 0.72.0-r2
