schema-version: 2.0.2

package:
  name: prometheus-3.7

advisories:
  - id: CGA-8fhv-mwg3-7xmg
    aliases:
      - CVE-2025-61729
      - GHSA-7c64-f9jr-v9h2
    events:
      - timestamp: 2025-12-05T04:51:25Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.7
            componentID: 21000c8380e1eaed
            componentName: stdlib
            componentVersion: go1.25.4
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2025-12-05T14:57:39Z
        type: true-positive-determination
        data:
          note: 'Govulncheck found vulnerable symbols in Go binaries at the following locations: in prometheus-3.7-3.7.3-r1.apk, at usr/bin/prometheus, usr/bin/prometheus, usr/bin/promtool, usr/bin/promtool.'
      - timestamp: 2025-12-05T21:08:33Z
        type: fixed
        data:
          fixed-version: 3.7.3-r2

  - id: CGA-98gv-5m6f-pp55
    aliases:
      - CVE-2025-58181
      - GHSA-j5w8-q4qc-rx2x
    events:
      - timestamp: 2025-11-22T20:17:32Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.7
            componentID: b3498b988dec8a8d
            componentName: golang.org/x/crypto
            componentVersion: v0.42.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2025-11-25T09:14:16Z
        type: fixed
        data:
          fixed-version: 3.7.3-r1

  - id: CGA-9vg2-cg26-8gg9
    aliases:
      - CVE-2025-47914
      - GHSA-f6x5-jh6r-wrfv
    events:
      - timestamp: 2025-11-22T20:17:31Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-3.7
            componentID: b3498b988dec8a8d
            componentName: golang.org/x/crypto
            componentVersion: v0.42.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2025-11-25T09:14:17Z
        type: fixed
        data:
          fixed-version: 3.7.3-r1
