schema-version: 2.0.2

package:
  name: prometheus-2.51

advisories:
  - id: CGA-26hv-mxh9-2cwp
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2025-03-06T03:23:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 09923d227f855e66
            componentName: stdlib
            componentVersion: go1.22.3
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-2768-3g7j-m8vq
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2025-03-06T03:23:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 09923d227f855e66
            componentName: stdlib
            componentVersion: go1.22.3
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-4mqm-wv84-cx26
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2025-03-06T03:23:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 09923d227f855e66
            componentName: stdlib
            componentVersion: go1.22.3
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-4vv6-2cv9-6w5x
    aliases:
      - CVE-2020-8559
      - GHSA-33c5-9fx5-fvjm
    events:
      - timestamp: 2024-04-25T14:20:28Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: c0dedc304f1b4e74
            componentName: k8s.io/apimachinery
            componentVersion: v0.29.2
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-6644-pfwr-qfqp
    aliases:
      - CVE-2024-36620
      - GHSA-q59j-vv4j-v33c
    events:
      - timestamp: 2025-03-06T03:22:47Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 3543ac7c41cd0c2f
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-7ff7-xf47-xjrv
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T03:22:59Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 694828771d7ba65d
            componentName: golang.org/x/oauth2
            componentVersion: v0.18.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-9fq5-q9cx-79p9
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2025-03-06T03:23:27Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 09923d227f855e66
            componentName: stdlib
            componentVersion: go1.22.3
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-c3jc-99h9-p7w7
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2025-03-06T03:23:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 09923d227f855e66
            componentName: stdlib
            componentVersion: go1.22.3
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-jcrg-9cgc-fpwg
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2025-03-06T03:22:50Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 3543ac7c41cd0c2f
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-jgrm-x9gc-mj5w
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T03:23:02Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 1c952e6f3b3f174f
            componentName: golang.org/x/crypto
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-mjmh-97p8-24r9
    aliases:
      - CVE-2024-6104
      - GHSA-v6v8-xj6m-xwqh
    events:
      - timestamp: 2025-03-06T03:22:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 6899554cffff5c7a
            componentName: github.com/hashicorp/go-retryablehttp
            componentVersion: v0.7.4
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-p2pf-f36q-wj2p
    aliases:
      - CVE-2024-35255
      - GHSA-m5vv-6r4h-3vj9
    events:
      - timestamp: 2025-03-06T03:23:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 7fb6278fa3304ad9
            componentName: github.com/Azure/azure-sdk-for-go/sdk/azidentity
            componentVersion: v1.5.1
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-phhv-vgmv-xgjg
    aliases:
      - CVE-2024-29018
      - GHSA-mq39-4gv4-mvpx
    events:
      - timestamp: 2024-03-22T13:57:44Z
        type: fixed
        data:
          fixed-version: 2.51.0-r1

  - id: CGA-qww7-8w6w-7fh5
    aliases:
      - CVE-2024-36623
      - GHSA-gh5c-3h97-2f3q
    events:
      - timestamp: 2025-03-06T03:22:49Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 3543ac7c41cd0c2f
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-r4vp-vpj2-fh9q
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2025-03-06T03:23:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 09923d227f855e66
            componentName: stdlib
            componentVersion: go1.22.3
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-xf98-hj58-8p3w
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-03-06T03:22:54Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 7ae5c3f99b3b466d
            componentName: golang.org/x/net
            componentVersion: v0.23.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-xgc8-q9r4-ff8v
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:29:28Z
        type: fixed
        data:
          fixed-version: 2.51.1-r1

  - id: CGA-xjj8-5x78-c849
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2025-03-06T03:22:52Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.51
            componentID: 1c952e6f3b3f174f
            componentName: golang.org/x/crypto
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
