schema-version: 2.0.2

package:
  name: prometheus-2.54

advisories:
  - id: CGA-7xmj-6426-54h9
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T03:06:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 24ce9dc662a6729c
            componentName: golang.org/x/crypto
            componentVersion: v0.25.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-8q2m-w6v7-qx6j
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T17:14:40Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0dfe49e0752f7c8a
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-09-12T20:12:02Z
        type: fixed
        data:
          fixed-version: 2.54.1-r1

  - id: CGA-95xf-x8fp-x4w8
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-03-06T03:06:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: bef577fa67e1544b
            componentName: stdlib
            componentVersion: go1.23.1
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-9r48-r866-vfpf
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-03-06T03:06:35Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0d00fb1d53faa8f2
            componentName: golang.org/x/net
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-cqmv-c2wf-h52r
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T17:14:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0dfe49e0752f7c8a
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-09-12T20:12:04Z
        type: fixed
        data:
          fixed-version: 2.54.1-r1

  - id: CGA-g3rq-6959-9qwh
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T03:06:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 5fdcf210cac24ddd
            componentName: golang.org/x/oauth2
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-gw99-2mwh-6pxv
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T17:14:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0dfe49e0752f7c8a
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-09-12T20:12:03Z
        type: fixed
        data:
          fixed-version: 2.54.1-r1

  - id: CGA-j2f4-33fv-qhxx
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2025-03-06T03:06:33Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 24ce9dc662a6729c
            componentName: golang.org/x/crypto
            componentVersion: v0.25.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-m2c6-cr9v-mgm6
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2024-08-14T01:00:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0acb39f961f5ff5c
            componentName: github.com/docker/docker
            componentVersion: v27.0.3+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-08-14T03:00:31Z
        type: fixed
        data:
          fixed-version: 2.54.0-r1
