schema-version: 2.0.2

package:
  name: prometheus-elasticsearch-exporter

advisories:
  - id: CGA-pjh4-p3cg-mm8f
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:02Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:31Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CGA-9jmm-frrc-j86w
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:47Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:16Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CGA-wxpj-97pc-mhgh
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-18T03:55:41Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CGA-wm28-v8fh-c97v
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-459x-mmxg-3jpc
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-5m34-594f-pg77
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T10:18:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: ff69c4097c2c475c
            componentName: golang.org/x/net
            componentVersion: v0.17.0
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-05-02T17:15:55Z
        type: fixed
        data:
          fixed-version: 1.7.0-r5

  - id: CGA-qf5j-xmhh-c2vm
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T07:13:26Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-pq99-78pr-3fvw
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-13T07:13:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-3x73-g6qc-6g4p
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-13T07:13:28Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-gv5w-g45c-6x7r
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T07:13:25Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-8qhf-2qrh-8p5x
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T07:13:26Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-vhr9-jw99-6wvc
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-16T11:02:03Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3
