schema-version: 2.0.2

package:
  name: prometheus-elasticsearch-exporter

advisories:
  - id: CGA-2rf2-jxw5-wmhh
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-08T09:19:33Z
        type: fixed
        data:
          fixed-version: 1.7.0-r8

  - id: CGA-39x9-cf49-9mvr
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-02-01T05:02:01Z
        type: fixed
        data:
          fixed-version: 1.8.0-r3

  - id: CGA-3x73-g6qc-6g4p
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-13T07:13:28Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-459x-mmxg-3jpc
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-5m34-594f-pg77
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T10:18:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: ff69c4097c2c475c
            componentName: golang.org/x/net
            componentVersion: v0.17.0
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-05-02T17:15:55Z
        type: fixed
        data:
          fixed-version: 1.7.0-r5

  - id: CGA-7vgj-84gv-68ch
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-02-01T05:01:56Z
        type: fixed
        data:
          fixed-version: 1.8.0-r3

  - id: CGA-7wcj-f8gh-3jjq
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-08T09:19:36Z
        type: fixed
        data:
          fixed-version: 1.7.0-r8

  - id: CGA-84q4-9p69-vx56
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T11:44:47Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: 29ecdee71b4aefd1
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:46:45Z
        type: fixed
        data:
          fixed-version: 1.7.0-r10

  - id: CGA-8qhf-2qrh-8p5x
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-13T07:13:26Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-9jmm-frrc-j86w
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:47Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:16Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CGA-c49h-28c2-cpwj
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T21:35:22Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: 111d5160079c907b
            componentName: golang.org/x/net
            componentVersion: v0.23.0
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-12-20T22:27:05Z
        type: fixed
        data:
          fixed-version: 1.8.0-r2

  - id: CGA-c57q-f6c6-9jj7
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T14:28:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: 227490eeb9c99fb1
            componentName: golang.org/x/crypto
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-12-13T04:17:17Z
        type: fixed
        data:
          fixed-version: 1.8.0-r1

  - id: CGA-c7x5-5gw4-jgr2
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T11:44:51Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: 29ecdee71b4aefd1
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:46:45Z
        type: fixed
        data:
          fixed-version: 1.7.0-r10

  - id: CGA-f4vc-jg93-hj75
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T08:27:13Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: ba2cf30d419f959b
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype

  - id: CGA-gv5w-g45c-6x7r
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-13T07:13:25Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-j53p-6jr3-6cc3
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T15:01:06Z
        type: fixed
        data:
          fixed-version: 1.7.0-r9

  - id: CGA-pjh4-p3cg-mm8f
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:02Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:31Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CGA-pq99-78pr-3fvw
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-13T07:13:27Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-qf5j-xmhh-c2vm
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-13T07:13:26Z
        type: fixed
        data:
          fixed-version: 1.7.0-r2

  - id: CGA-rv65-5hp4-cgw9
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-10T11:44:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-elasticsearch-exporter
            componentID: 29ecdee71b4aefd1
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/elasticsearch_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:46:44Z
        type: fixed
        data:
          fixed-version: 1.7.0-r10

  - id: CGA-vhr9-jw99-6wvc
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-16T11:02:03Z
        type: fixed
        data:
          fixed-version: 1.7.0-r3

  - id: CGA-wm28-v8fh-c97v
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-wxpj-97pc-mhgh
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-18T03:55:41Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7
