schema-version: 2.0.2

package:
  name: prometheus-mysqld-exporter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:29Z
        type: fixed
        data:
          fixed-version: 0.15.0-r6

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:06Z
        type: fixed
        data:
          fixed-version: 0.15.0-r6

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:00Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:02Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T11:01:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 26e4faaf951e64c3
            componentName: golang.org/x/net
            componentVersion: v0.17.0
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T10:02:56Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CVE-2023-45290
    aliases:
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T10:02:56Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-01-27T07:11:14Z
        type: fixed
        data:
          fixed-version: 0.15.1-r2

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T10:02:57Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T10:02:58Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CVE-2024-24785
    aliases:
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T10:02:59Z
        type: fixed
        data:
          fixed-version: 0.15.1-r3

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T08:19:23Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mysqld-exporter
            componentID: 89d3a797853f608f
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/mysqld_exporter
            scanner: grype
      - timestamp: 2024-03-31T01:37:49Z
        type: fixed
        data:
          fixed-version: 0.15.1-r4
