schema-version: 2.0.2

package:
  name: prometheus-mongodb-exporter

advisories:
  - id: CGA-22mg-v3w8-qq3v
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T13:07:14Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mongodb-exporter
            componentID: 5c84dc9d08f4a3ca
            componentName: golang.org/x/crypto
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/mongodb_exporter
            scanner: grype
      - timestamp: 2024-12-13T08:24:55Z
        type: fixed
        data:
          fixed-version: 0.43.0-r1

  - id: CGA-2jg2-3495-36r2
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:35:57Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-35qm-fj88-wvmq
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T08:01:58Z
        type: fixed
        data:
          fixed-version: 0.40.0-r10

  - id: CGA-4hv8-22hm-73x5
    aliases:
      - CVE-2023-45289
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:19:52Z
        type: fixed
        data:
          fixed-version: 0.40.0-r3

  - id: CGA-5rhj-v9ph-5738
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T23:09:58Z
        type: fixed
        data:
          fixed-version: 0.43.1-r2

  - id: CGA-656j-q4r3-286q
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T08:02:02Z
        type: fixed
        data:
          fixed-version: 0.40.0-r10

  - id: CGA-9jcm-w6xf-h985
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-11T00:18:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mongodb-exporter
            componentID: 0f854ffdbd2b3ce0
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/mongodb_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:03:45Z
        type: fixed
        data:
          fixed-version: 0.40.0-r12

  - id: CGA-c973-4p9p-p93f
    aliases:
      - CVE-2024-24785
      - GHSA-j6m3-gc37-6r6q
    events:
      - timestamp: 2024-03-12T09:19:51Z
        type: fixed
        data:
          fixed-version: 0.40.0-r3

  - id: CGA-f93g-j8ww-j5q7
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T23:10:04Z
        type: fixed
        data:
          fixed-version: 0.43.1-r2

  - id: CGA-g7jw-h9p6-739w
    aliases:
      - CVE-2023-39325
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:18Z
        type: fixed
        data:
          fixed-version: 0.39.0-r4

  - id: CGA-j298-hqrf-m285
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T11:12:57Z
        type: fixed
        data:
          fixed-version: 0.40.0-r11

  - id: CGA-jj9j-mxp6-xrmf
    aliases:
      - CVE-2023-45290
      - GHSA-rr6r-cfgf-gc6h
    events:
      - timestamp: 2024-03-12T09:19:49Z
        type: fixed
        data:
          fixed-version: 0.40.0-r3

  - id: CGA-m3vv-4q63-r828
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T15:23:48Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mongodb-exporter
            componentID: 5e380b4a81d2d328
            componentName: golang.org/x/net
            componentVersion: v0.32.0
            componentType: go-module
            componentLocation: /usr/bin/mongodb_exporter
            scanner: grype
      - timestamp: 2024-12-20T05:16:29Z
        type: fixed
        data:
          fixed-version: 0.43.1-r1

  - id: CGA-m5q5-g7r2-f2rw
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2023-12-22T15:02:11Z
        type: fixed
        data:
          fixed-version: 0.40.0-r2

  - id: CGA-mq27-jwp9-458c
    aliases:
      - CVE-2024-24783
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:19:50Z
        type: fixed
        data:
          fixed-version: 0.40.0-r3

  - id: CGA-p83f-g28f-95rw
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-11T00:18:36Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mongodb-exporter
            componentID: 0f854ffdbd2b3ce0
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/mongodb_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:03:45Z
        type: fixed
        data:
          fixed-version: 0.40.0-r12

  - id: CGA-pvm6-h93v-9372
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-26T11:17:48Z
        type: fixed
        data:
          fixed-version: 0.40.0-r6

  - id: CGA-v9hr-p987-5x5g
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T13:21:43Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mongodb-exporter
            componentID: 049d39ff2a8c84ae
            componentName: google.golang.org/protobuf
            componentVersion: v1.31.0
            componentType: go-module
            componentLocation: /usr/bin/mongodb_exporter
            scanner: grype
      - timestamp: 2024-03-16T11:02:18Z
        type: fixed
        data:
          fixed-version: 0.40.0-r4

  - id: CGA-vxxp-f6x4-9j8x
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:35:58Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-w5wf-xvg6-5j4g
    aliases:
      - CVE-2023-3978
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:58Z
        type: fixed
        data:
          fixed-version: 0.39.0-r4

  - id: CGA-wfch-7r35-58j8
    aliases:
      - CVE-2024-24784
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:19:50Z
        type: fixed
        data:
          fixed-version: 0.40.0-r3

  - id: CGA-wrm2-2vw9-27x6
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-11T00:18:41Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-mongodb-exporter
            componentID: 0f854ffdbd2b3ce0
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/mongodb_exporter
            scanner: grype
      - timestamp: 2024-09-12T20:03:46Z
        type: fixed
        data:
          fixed-version: 0.40.0-r12
