schema-version: 2.0.2

package:
  name: prometheus-stackdriver-exporter

advisories:
  - id: CVE-2022-41723
    aliases:
      - GHSA-vvpx-j8f3-3w6h
    events:
      - timestamp: 2023-05-02T22:52:07Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used

  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2024-02-14T14:29:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 68785c7367cc7b8b
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:29Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CVE-2023-39326
    aliases:
      - GHSA-9f76-wg39-x86h
    events:
      - timestamp: 2024-02-17T07:42:24Z
        type: fixed
        data:
          fixed-version: 0.14.1-r7

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2024-02-14T14:29:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 68785c7367cc7b8b
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:28Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2024-02-14T14:29:40Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 68785c7367cc7b8b
            componentName: golang.org/x/net
            componentVersion: v0.10.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:29Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:22Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:24Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45285
    aliases:
      - GHSA-5f94-vhjq-rpg8
    events:
      - timestamp: 2024-02-17T07:42:26Z
        type: fixed
        data:
          fixed-version: 0.14.1-r7

  - id: CVE-2023-45288
    aliases:
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:17:38Z
        type: fixed
        data:
          fixed-version: 0.15.0-r1

  - id: CVE-2023-48795
    aliases:
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-02-14T14:29:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: 3bd243bcbd49b349
            componentName: golang.org/x/crypto
            componentVersion: v0.8.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:28Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8

  - id: CVE-2024-24786
    aliases:
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T09:21:55Z
        type: fixed
        data:
          fixed-version: 0.15.0-r0

  - id: CVE-2024-24787
    aliases:
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T13:09:01Z
        type: fixed
        data:
          fixed-version: 0.15.0-r3

  - id: GHSA-m425-mq94-257g
    events:
      - timestamp: 2024-02-14T14:29:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-stackdriver-exporter
            componentID: dbbbdfaffeed19a1
            componentName: google.golang.org/grpc
            componentVersion: v1.55.0
            componentType: go-module
            componentLocation: /usr/bin/stackdriver_exporter
            scanner: grype
      - timestamp: 2024-02-17T08:38:28Z
        type: fixed
        data:
          fixed-version: 0.14.1-r8
