schema-version: 2.0.2

package:
  name: prometheus-2.45

advisories:
  - id: CVE-2023-40577
    aliases:
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2024-03-02T08:06:12Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.45-bitnami-compat
            componentID: 4f87f7fa3862464f
            componentName: github.com/prometheus/alertmanager
            componentVersion: v0.25.0
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2024-03-04T17:24:05Z
        type: fixed
        data:
          fixed-version: 2.45.3-r2

  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T09:22:02Z
        type: fixed
        data:
          fixed-version: 2.45.3-r3

  - id: CVE-2024-24783
    aliases:
      - GHSA-3q2c-pvp5-3cqp
    events:
      - timestamp: 2024-03-12T09:22:01Z
        type: fixed
        data:
          fixed-version: 2.45.3-r3

  - id: CVE-2024-24784
    aliases:
      - GHSA-fgq5-q76c-gx78
    events:
      - timestamp: 2024-03-12T09:22:02Z
        type: fixed
        data:
          fixed-version: 2.45.3-r3

  - id: GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2024-03-02T08:06:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.45-bitnami-compat
            componentID: cf0b0f7160c2250e
            componentName: github.com/docker/docker
            componentVersion: v24.0.2+incompatible
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
      - timestamp: 2024-03-04T17:24:05Z
        type: fixed
        data:
          fixed-version: 2.45.3-r2
