schema-version: 2.0.2

package:
  name: prometheus-2.54

advisories:
  - id: CGA-cqmv-c2wf-h52r
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-10T17:14:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0dfe49e0752f7c8a
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-gw99-2mwh-6pxv
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-10T17:14:38Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0dfe49e0752f7c8a
            componentName: stdlib
            componentVersion: go1.23.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype

  - id: CGA-m2c6-cr9v-mgm6
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2024-08-14T01:00:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.54
            componentID: 0acb39f961f5ff5c
            componentName: github.com/docker/docker
            componentVersion: v27.0.3+incompatible
            componentType: go-module
            componentLocation: /usr/bin/prometheus
            scanner: grype
      - timestamp: 2024-08-14T03:00:31Z
        type: fixed
        data:
          fixed-version: 2.54.0-r1
