schema-version: 2.0.2

package:
  name: prometheus-nats-exporter

advisories:
  - id: CGA-25q5-6rhp-m9gm
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:36:05Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-3f2h-wp46-vw55
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-08T10:03:08Z
        type: fixed
        data:
          fixed-version: 0.15.0-r2

  - id: CGA-3h7m-mfpr-xcw9
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:36:04Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-42rq-jh8c-g48r
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T22:04:59Z
        type: fixed
        data:
          fixed-version: 0.16.0-r2

  - id: CGA-4qxm-6w68-6295
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T22:33:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: 4a7c8e3b29eb9acc
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2025-02-09T18:25:45Z
        type: fixed
        data:
          fixed-version: 0.16.0-r3

  - id: CGA-6q25-m67x-f4vx
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-11T03:41:32Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: 0a01bbe87a6e8a68
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2024-09-18T20:19:58Z
        type: fixed
        data:
          fixed-version: 0.15.0-r4

  - id: CGA-7f9v-f5c5-2rp7
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2024-01-15T15:49:17Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: bd4bcb53f8e8992f
            componentName: golang.org/x/crypto
            componentVersion: v0.14.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2024-01-26T07:12:10Z
        type: fixed
        data:
          fixed-version: 0.14.0-r1

  - id: CGA-7wpj-8gh8-7j25
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-08T10:03:06Z
        type: fixed
        data:
          fixed-version: 0.15.0-r2

  - id: CGA-fhp9-9vfm-8mr3
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-14T14:19:15Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: 00a3000ee14eda5f
            componentName: google.golang.org/protobuf
            componentVersion: v1.30.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2024-04-18T14:12:21Z
        type: fixed
        data:
          fixed-version: 0.15.0-r0

  - id: CGA-h56v-rhh8-c5fp
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T22:04:55Z
        type: fixed
        data:
          fixed-version: 0.16.0-r2

  - id: CGA-j77p-5mj2-4mq2
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:21:00Z
        type: fixed
        data:
          fixed-version: 0.14.0-r3

  - id: CGA-m3mc-28mv-w23r
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-15T10:19:13Z
        type: fixed
        data:
          fixed-version: 0.15.0-r1

  - id: CGA-pxmm-mp8g-p3cv
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-11T03:41:27Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: 0a01bbe87a6e8a68
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2024-09-18T20:19:56Z
        type: fixed
        data:
          fixed-version: 0.15.0-r4

  - id: CGA-q5m3-w6cw-65gh
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-15T10:19:12Z
        type: fixed
        data:
          fixed-version: 0.15.0-r1

  - id: CGA-v2j4-x3gm-wfpw
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-11T03:41:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: 0a01bbe87a6e8a68
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2024-09-18T20:19:57Z
        type: fixed
        data:
          fixed-version: 0.15.0-r4

  - id: CGA-xcm4-3q7c-8qgg
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T18:06:59Z
        type: fixed
        data:
          fixed-version: 0.15.0-r3

  - id: CGA-xg63-rghc-rjx3
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T10:11:24Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-nats-exporter
            componentID: 50e485fb9dd8eea1
            componentName: golang.org/x/crypto
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/prometheus-nats-exporter
            scanner: grype
      - timestamp: 2024-12-12T18:14:32Z
        type: fixed
        data:
          fixed-version: 0.16.0-r1
