schema-version: 2.0.2

package:
  name: swagger

advisories:
  - id: CGA-244v-rj3j-2x42
    aliases:
      - GHSA-fv92-fjc5-jj9h
    events:
      - timestamp: 2025-06-28T13:23:47Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 3b2480a4c29fdd53
            componentName: github.com/go-viper/mapstructure/v2
            componentVersion: v2.2.1
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-06-28T17:37:26Z
        type: fixed
        data:
          fixed-version: 0.32.3-r1

  - id: CGA-2cqg-73p5-qx6r
    aliases:
      - CVE-2025-47907
      - GHSA-j5pm-7495-qmr3
    events:
      - timestamp: 2025-08-09T14:56:52Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 57390c11cbb57564
            componentName: stdlib
            componentVersion: go1.24.5
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-08-10T03:25:39Z
        type: fixed
        data:
          fixed-version: 0.32.3-r3

  - id: CGA-6835-6x7f-2fh3
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-11T00:33:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 004d0df15437e630
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2024-09-19T02:34:22Z
        type: fixed
        data:
          fixed-version: 0.31.0-r3

  - id: CGA-9q32-j7wq-65cj
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-11T00:33:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 004d0df15437e630
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2024-09-19T02:34:21Z
        type: fixed
        data:
          fixed-version: 0.31.0-r3

  - id: CGA-9x2h-9prf-gjmj
    aliases:
      - CVE-2024-45341
      - GHSA-3f6r-qh9c-x6mm
    events:
      - timestamp: 2025-01-31T20:34:18Z
        type: fixed
        data:
          fixed-version: 0.31.0-r5

  - id: CGA-f276-g75g-vmrv
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-01-31T20:34:16Z
        type: fixed
        data:
          fixed-version: 0.31.0-r5

  - id: CGA-f9gf-crqf-8ppm
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T16:34:31Z
        type: fixed
        data:
          fixed-version: 0.31.0-r1

  - id: CGA-fhv8-h985-cm68
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:31:52Z
        type: fixed
        data:
          fixed-version: 0.30.5-r1

  - id: CGA-fm93-c93m-6whh
    aliases:
      - CVE-2025-22866
      - GHSA-3whm-j4xm-rv8x
    events:
      - timestamp: 2025-02-08T09:09:58Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 4269f6ae9b460286
            componentName: stdlib
            componentVersion: go1.23.5
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-02-09T23:33:17Z
        type: fixed
        data:
          fixed-version: 0.31.0-r6

  - id: CGA-h5mq-674r-j37p
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T16:34:32Z
        type: fixed
        data:
          fixed-version: 0.31.0-r1

  - id: CGA-hqff-7g49-h99w
    aliases:
      - CVE-2024-24791
      - GHSA-hw49-2p59-3mhj
    events:
      - timestamp: 2024-07-04T17:08:55Z
        type: fixed
        data:
          fixed-version: 0.31.0-r2

  - id: CGA-hxgp-g75j-m73g
    aliases:
      - CVE-2025-47914
      - GHSA-f6x5-jh6r-wrfv
    events:
      - timestamp: 2025-11-22T03:31:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 589ee6ba62ccdcc4
            componentName: golang.org/x/crypto
            componentVersion: v0.41.0
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-11-22T07:46:03Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Govulncheck found no affected symbols in the scanned Go binaries.

  - id: CGA-j2vp-3c9r-q5h4
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T11:45:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: daf73e3f4738786a
            componentName: golang.org/x/crypto
            componentVersion: v0.31.0
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-03-12T04:44:16Z
        type: fixed
        data:
          fixed-version: 0.31.0-r7

  - id: CGA-vwpg-pfrp-jc2x
    aliases:
      - CVE-2025-22871
      - GHSA-g9pc-8g42-g6vq
    events:
      - timestamp: 2025-04-10T16:36:34Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: d86abb6b5657cf8d
            componentName: stdlib
            componentVersion: go1.24.1
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-04-11T16:13:11Z
        type: fixed
        data:
          fixed-version: 0.31.0-r8

  - id: CGA-w359-g9jm-pvf3
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-11T00:33:06Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 004d0df15437e630
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2024-09-19T02:34:22Z
        type: fixed
        data:
          fixed-version: 0.31.0-r3

  - id: CGA-w6xm-9q8w-7v74
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T13:12:03Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: b233f62d3ae617d3
            componentName: golang.org/x/crypto
            componentVersion: v0.23.0
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2024-12-13T03:45:39Z
        type: fixed
        data:
          fixed-version: 0.31.0-r4

  - id: CGA-wmg6-q42h-63f8
    aliases:
      - CVE-2025-58187
      - GHSA-frhw-mqj2-wxw2
    events:
      - timestamp: 2025-11-02T20:49:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 976d23ea8f1b387c
            componentName: stdlib
            componentVersion: go1.25.2
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-11-03T09:26:50Z
        type: fixed
        data:
          fixed-version: 0.33.1-r1

  - id: CGA-x9hg-g6r5-h938
    aliases:
      - CVE-2025-47910
      - GHSA-8pjc-487g-w6p2
    events:
      - timestamp: 2025-09-24T07:28:00Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: b8338edd235fe7b4
            componentName: stdlib
            componentVersion: go1.25.0
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
      - timestamp: 2025-09-24T09:44:47Z
        type: fixed
        data:
          fixed-version: 0.32.3-r6

  - id: CGA-xvhh-qrqm-v444
    aliases:
      - CVE-2025-58181
      - GHSA-j5w8-q4qc-rx2x
    events:
      - timestamp: 2025-11-22T03:31:54Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: swagger
            componentID: 589ee6ba62ccdcc4
            componentName: golang.org/x/crypto
            componentVersion: v0.41.0
            componentType: go-module
            componentLocation: /usr/bin/swagger
            scanner: grype
