schema-version: 2.0.2

package:
  name: swagger

advisories:
  - id: CGA-f9gf-crqf-8ppm
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T16:34:31Z
        type: fixed
        data:
          fixed-version: 0.31.0-r1

  - id: CGA-fhv8-h985-cm68
    aliases:
      - CVE-2023-45288
      - GHSA-4v7x-pqxf-cx7m
    events:
      - timestamp: 2024-04-13T07:31:52Z
        type: fixed
        data:
          fixed-version: 0.30.5-r1
