schema-version: 2.0.2

package:
  name: traefik

advisories:
  - id: CGA-2qh3-v6v9-6cm7
    aliases:
      - CVE-2022-46153
      - GHSA-468w-8x39-gj5v
    events:
      - timestamp: 2023-01-29T16:56:03Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used

  - id: CGA-33hf-4652-fxhq
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2025-03-06T04:09:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: f2f00c97cba24f08
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-54jw-54r8-r76p
    aliases:
      - CVE-2024-24790
      - GHSA-49gw-vxvf-fc2g
    events:
      - timestamp: 2024-06-07T12:09:03Z
        type: fixed
        data:
          fixed-version: 3.0.1-r1

  - id: CGA-5rw9-rrmv-pmfr
    aliases:
      - CVE-2024-35255
      - GHSA-m5vv-6r4h-3vj9
    events:
      - timestamp: 2024-06-12T08:04:06Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: c2c46d64fb8dda79
            componentName: github.com/Azure/azure-sdk-for-go/sdk/azidentity
            componentVersion: v1.5.2
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-06-14T22:00:28Z
        type: fixed
        data:
          fixed-version: 3.0.2-r1

  - id: CGA-8ff8-px3p-27h2
    aliases:
      - CVE-2023-44487
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-13T12:27:29Z
        type: fixed
        data:
          fixed-version: 2.10.5-r0

  - id: CGA-8pcv-r7p9-7rjm
    aliases:
      - GHSA-7jmw-8259-q9jx
    events:
      - timestamp: 2024-06-12T08:35:03Z
        type: fixed
        data:
          fixed-version: 3.0.2-r0

  - id: CGA-95f4-3hhv-m8x4
    aliases:
      - CVE-2024-24787
      - GHSA-5fq7-4mxc-535h
    events:
      - timestamp: 2024-05-14T12:14:21Z
        type: fixed
        data:
          fixed-version: 3.0.0-r2

  - id: CGA-96rm-cc48-29vq
    aliases:
      - GHSA-f7cq-5v43-8pwp
    events:
      - timestamp: 2024-05-25T08:34:38Z
        type: fixed
        data:
          fixed-version: 3.0.1-r0

  - id: CGA-9vg5-h493-cxr7
    aliases:
      - CVE-2024-28180
      - GHSA-c5q2-7r4c-mv6g
    events:
      - timestamp: 2024-03-08T07:35:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: 9cc2f8c00b9c6173
            componentName: github.com/go-jose/go-jose/v3
            componentVersion: v3.0.1
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-03-08T09:33:21Z
        type: fixed
        data:
          fixed-version: 2.11.0-r2
      - timestamp: 2024-06-01T08:08:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: fd6f2d7cb1be2869
            componentName: gopkg.in/square/go-jose.v2
            componentVersion: v2.5.1
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-06-12T07:05:14Z
        type: pending-upstream-fix
        data:
          note: This vulnerability has recently updated the list of affected packages. Unfortunately the new affected package 'gopkg.in/square/go-jose.v2' is currently used by many indirect dependencies to this package which makes impossible to fix it without upstream code changes.

  - id: CGA-fj5h-2qwj-2xpj
    aliases:
      - CVE-2024-24789
      - GHSA-236w-p7wf-5ph8
    events:
      - timestamp: 2024-06-07T12:09:09Z
        type: fixed
        data:
          fixed-version: 3.0.1-r1

  - id: CGA-fm2r-q69f-j8r4
    aliases:
      - GHSA-2c7c-3mj9-8fqh
    events:
      - timestamp: 2023-11-22T16:41:41Z
        type: fixed
        data:
          fixed-version: 2.10.5-r1

  - id: CGA-fmqj-vc6j-h8g6
    aliases:
      - CVE-2024-24786
      - GHSA-8r3f-844c-mc37
    events:
      - timestamp: 2024-03-17T14:48:47Z
        type: fixed
        data:
          fixed-version: 2.11.0-r3

  - id: CGA-fw5f-2wcr-6w42
    aliases:
      - CVE-2024-36620
      - GHSA-q59j-vv4j-v33c
    events:
      - timestamp: 2025-03-06T04:09:30Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: f2f00c97cba24f08
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-gmc5-3w2q-4gmp
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-03-06T04:10:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: 6420513800130cc0
            componentName: golang.org/x/net
            componentVersion: v0.26.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-gmgf-ghq8-4wmm
    aliases:
      - CVE-2023-48795
      - GHSA-45x7-px36-x8w8
    events:
      - timestamp: 2023-12-20T01:55:41Z
        type: fixed
        data:
          fixed-version: 2.10.7-r2

  - id: CGA-hrj8-f7rj-q77v
    aliases:
      - CVE-2024-45410
      - GHSA-62c8-mh53-4cqv
    events:
      - timestamp: 2025-03-06T04:10:20Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: c5ed7c274d8c6312
            componentName: traefik
            componentVersion: 3.0.3-r0
            componentType: apk
            componentLocation: /.PKGINFO
            scanner: grype

  - id: CGA-j29h-jxmh-xmv5
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T04:10:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: 9d1e9d7cdd54eea4
            componentName: golang.org/x/oauth2
            componentVersion: v0.21.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-j2wv-fjf9-3p6w
    aliases:
      - CVE-2024-52003
      - GHSA-h924-8g65-j9wg
    events:
      - timestamp: 2025-03-06T04:10:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: c5ed7c274d8c6312
            componentName: traefik
            componentVersion: 3.0.3-r0
            componentType: apk
            componentLocation: /.PKGINFO
            scanner: grype

  - id: CGA-j934-88qp-fh2j
    aliases:
      - CVE-2020-8559
      - GHSA-33c5-9fx5-fvjm
    events:
      - timestamp: 2024-04-25T14:06:08Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: cf3d61d8744baa2e
            componentName: k8s.io/apimachinery
            componentVersion: v0.26.3
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-jm25-2pcj-cj59
    aliases:
      - CVE-2023-45284
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:39:51Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-jw9h-hmw7-8m6p
    aliases:
      - CVE-2023-2253
      - GHSA-hqxw-f8mx-cpmw
    events:
      - timestamp: 2023-05-17T21:12:08Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2

  - id: CGA-mxj7-wqgf-w737
    aliases:
      - CVE-2024-39321
      - GHSA-gxrv-wf35-62w9
    events:
      - timestamp: 2025-03-06T04:09:45Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: c5ed7c274d8c6312
            componentName: traefik
            componentVersion: 3.0.3-r0
            componentType: apk
            componentLocation: /.PKGINFO
            scanner: grype

  - id: CGA-pcmx-mv9c-w8wg
    aliases:
      - GHSA-7f4j-64p6-5h5v
    events:
      - timestamp: 2024-04-16T07:22:07Z
        type: fixed
        data:
          fixed-version: 2.11.2-r0

  - id: CGA-pcx8-wpwg-h5mw
    aliases:
      - CVE-2024-36623
      - GHSA-gh5c-3h97-2f3q
    events:
      - timestamp: 2025-03-06T04:09:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: f2f00c97cba24f08
            componentName: github.com/docker/docker
            componentVersion: v25.0.5+incompatible
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-pgj7-gxpp-3mj7
    aliases:
      - CVE-2024-24557
      - GHSA-xw73-rw38-6vjc
    events:
      - timestamp: 2024-03-21T11:44:20Z
        type: fixed
        data:
          fixed-version: 2.11.0-r4

  - id: CGA-ppmm-35w3-p2w7
    aliases:
      - CVE-2023-47106
      - GHSA-fvhj-4qfh-q2hm
    events:
      - timestamp: 2023-12-04T21:24:39Z
        type: fixed
        data:
          fixed-version: 2.10.6-r0

  - id: CGA-prwh-gpv3-3fm5
    aliases:
      - GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2023-10-31T20:04:04Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is in the container runtime itself, not clients of the container runtime.

  - id: CGA-qg68-593j-q573
    aliases:
      - CVE-2022-40716
      - GHSA-m69r-9g56-7mv8
    events:
      - timestamp: 2023-03-07T16:52:26Z
        type: fixed
        data:
          fixed-version: 2.9.8-r1

  - id: CGA-r7v2-xp2f-mjxf
    aliases:
      - GHSA-rvj4-q8q5-8grf
    events:
      - timestamp: 2024-06-21T10:21:28Z
        type: fixed
        data:
          fixed-version: 3.0.3-r0

  - id: CGA-rp6h-8rr4-w226
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2025-03-06T04:10:01Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: cb668007f25f75ee
            componentName: golang.org/x/crypto
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-wgv8-rh95-48wv
    aliases:
      - CVE-2024-28869
      - GHSA-4vwx-54mw-vqfw
    events:
      - timestamp: 2024-04-13T07:34:54Z
        type: fixed
        data:
          fixed-version: 2.11.2-r0

  - id: CGA-wh5m-wq28-33q8
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T04:10:49Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik
            componentID: cb668007f25f75ee
            componentName: golang.org/x/crypto
            componentVersion: v0.24.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-wvcm-rvw5-5gm7
    aliases:
      - CVE-2024-24788
      - GHSA-2jwv-jmq4-4j3r
    events:
      - timestamp: 2024-05-14T12:14:24Z
        type: fixed
        data:
          fixed-version: 3.0.0-r2

  - id: CGA-wvxq-mvwq-53p9
    aliases:
      - CVE-2023-49295
      - GHSA-ppxx-5m9h-6vxf
    events:
      - timestamp: 2024-01-25T07:13:41Z
        type: fixed
        data:
          fixed-version: 2.10.7-r3

  - id: CGA-wxx9-7c6r-jp6p
    aliases:
      - CVE-2023-47124
      - GHSA-8g85-whqh-cr2f
    events:
      - timestamp: 2023-12-04T21:24:09Z
        type: fixed
        data:
          fixed-version: 2.10.6-r0

  - id: CGA-x38p-p6h4-33cc
    aliases:
      - CVE-2021-41803
      - GHSA-hr3v-8cp3-68rf
    events:
      - timestamp: 2023-03-07T16:51:57Z
        type: fixed
        data:
          fixed-version: 2.9.8-r1

  - id: CGA-x9v6-j2gv-85v5
    aliases:
      - CVE-2023-45283
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:39:49Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CGA-xjvj-jwv7-22q2
    aliases:
      - CVE-2022-23469
      - GHSA-h2ph-vhm7-g4hp
    events:
      - timestamp: 2023-01-29T16:56:03Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used

  - id: CGA-xqg4-xfv5-m4j4
    aliases:
      - CVE-2023-47633
      - GHSA-6fwg-jrfw-ff7p
    events:
      - timestamp: 2023-12-04T21:24:28Z
        type: fixed
        data:
          fixed-version: 2.10.6-r0
