schema-version: 2.0.2

package:
  name: traefik-3.4

advisories:
  - id: CGA-8m4r-jcr7-2v5w
    aliases:
      - CVE-2025-4673
      - GHSA-62jj-gr2r-5c34
    events:
      - timestamp: 2025-06-14T20:17:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.4
            componentID: 4ee66a36df6f2b93
            componentName: stdlib
            componentVersion: go1.24.3
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2025-06-15T05:46:49Z
        type: fixed
        data:
          fixed-version: 3.4.1-r1

  - id: CGA-h53x-hv5m-3f88
    aliases:
      - CVE-2025-22874
      - GHSA-6f52-wpx2-hvf2
    events:
      - timestamp: 2025-06-14T20:17:45Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.4
            componentID: 4ee66a36df6f2b93
            componentName: stdlib
            componentVersion: go1.24.3
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
