schema-version: 2.0.2

package:
  name: traefik-3.2

advisories:
  - id: CGA-42fq-cf7c-9r5v
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2024-12-19T10:10:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: 007fe04a37a21838
            componentName: golang.org/x/net
            componentVersion: v0.30.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-12-20T16:20:32Z
        type: fixed
        data:
          fixed-version: 3.2.3-r1

  - id: CGA-7wcq-cw6w-3j7m
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2024-12-12T08:07:03Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: f5706a35027a8ce1
            componentName: golang.org/x/crypto
            componentVersion: v0.28.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-12-12T16:26:43Z
        type: fixed
        data:
          fixed-version: 3.2.2-r1

  - id: CGA-9w2r-526h-q76r
    aliases:
      - CVE-2024-53259
      - GHSA-px8v-pp82-rcvr
    events:
      - timestamp: 2024-12-03T11:13:39Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: a925b3ff0c8ef4fb
            componentName: github.com/quic-go/quic-go
            componentVersion: v0.47.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-12-03T12:12:34Z
        type: fixed
        data:
          fixed-version: 3.2.1-r1

  - id: CGA-j4v3-whmm-486j
    aliases:
      - CVE-2024-28180
      - GHSA-c5q2-7r4c-mv6g
    events:
      - timestamp: 2024-11-01T17:01:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: 5c0b53c63191a528
            componentName: gopkg.in/square/go-jose.v2
            componentVersion: v2.5.1
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-11-14T10:18:30Z
        type: pending-upstream-fix
        data:
          note: 'The gopkg.in/square/go-jose.v2 dependency is archived and will not be fixed as can be seen here fro the advisory database: https://github.com/advisories/GHSA-c5q2-7r4c-mv6g The upstream maintainers must implement the fix. '
      - timestamp: 2025-01-06T12:45:36Z
        type: fixed
        data:
          fixed-version: 3.2.4-r0

  - id: CGA-pw97-9g4p-mg7w
    aliases:
      - CVE-2024-51744
      - GHSA-29wx-vh33-7x7r
    events:
      - timestamp: 2024-11-05T10:03:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: 18620a0c8e001111
            componentName: github.com/golang-jwt/jwt/v4
            componentVersion: v4.5.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-11-08T09:33:40Z
        type: fixed
        data:
          fixed-version: 3.2.0-r1
