schema-version: 2.0.2

package:
  name: traefik-3.6

advisories:
  - id: CGA-322r-3mgx-6wfh
    aliases:
      - CVE-2025-47914
      - GHSA-f6x5-jh6r-wrfv
    events:
      - timestamp: 2025-11-22T01:30:07Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.6
            componentID: 40755dca49385309
            componentName: golang.org/x/crypto
            componentVersion: v0.43.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
