schema-version: 2.0.2

package:
  name: traefik-3.1

advisories:
  - id: CGA-25ff-548g-m242
    aliases:
      - CVE-2024-51744
      - GHSA-29wx-vh33-7x7r
    events:
      - timestamp: 2025-03-06T04:24:56Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 18620a0c8e001111
            componentName: github.com/golang-jwt/jwt/v4
            componentVersion: v4.5.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-28fw-5w49-gvr3
    aliases:
      - CVE-2024-34158
      - GHSA-j7vj-rw65-4v26
    events:
      - timestamp: 2024-09-11T00:15:06Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 3704a7618aee5579
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-09-16T18:23:35Z
        type: fixed
        data:
          fixed-version: 3.1.3-r0

  - id: CGA-3c86-jf8f-h6c6
    aliases:
      - GHSA-hxr6-2p24-hf98
    events:
      - timestamp: 2025-03-06T04:25:02Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 636946a3385a7fb4
            componentName: github.com/traefik/traefik/v3
            componentVersion: v3.1.7
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-3cgm-pfmw-w78m
    aliases:
      - CVE-2024-45338
      - GHSA-w32m-9786-jp63
    events:
      - timestamp: 2025-03-06T04:24:46Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 93a3fca34dbc7e0b
            componentName: golang.org/x/net
            componentVersion: v0.29.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-4p2p-rr3x-96xx
    aliases:
      - CVE-2024-45337
      - GHSA-v778-237x-gjrc
    events:
      - timestamp: 2025-03-06T04:24:44Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: e5404054c2c4e6aa
            componentName: golang.org/x/crypto
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-62c9-w2qq-2p5c
    aliases:
      - CVE-2024-53259
      - GHSA-px8v-pp82-rcvr
    events:
      - timestamp: 2025-03-06T04:25:07Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: f4391141ed05dc47
            componentName: github.com/quic-go/quic-go
            componentVersion: v0.47.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-6q77-rm5j-xgw7
    aliases:
      - CVE-2024-34155
      - GHSA-8xfx-rj4p-23jm
    events:
      - timestamp: 2024-09-11T00:15:03Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 3704a7618aee5579
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-09-16T18:23:36Z
        type: fixed
        data:
          fixed-version: 3.1.3-r0

  - id: CGA-6w58-8v92-qmq7
    aliases:
      - CVE-2024-28180
      - GHSA-c5q2-7r4c-mv6g
    events:
      - timestamp: 2024-07-24T17:18:37Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: a023d85a660d780d
            componentName: gopkg.in/square/go-jose.v2
            componentVersion: v2.5.1
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-07-25T15:38:42Z
        type: pending-upstream-fix
        data:
          note: There is no fix for dependency gopkg.in/square/go-jose.v2 as it is unmaintained, and to fix this vulnerability would require non-trivial upstream code changes to replace the affected dependency.

  - id: CGA-8jfg-2qgp-rhm5
    aliases:
      - CVE-2024-45336
      - GHSA-7wrw-r4p8-38rx
    events:
      - timestamp: 2025-03-06T04:25:10Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 2e0a62075c4872f2
            componentName: stdlib
            componentVersion: go1.23.2
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-952v-x2mh-mj4p
    aliases:
      - CVE-2025-22869
    events:
      - timestamp: 2025-03-06T04:24:53Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: e5404054c2c4e6aa
            componentName: golang.org/x/crypto
            componentVersion: v0.27.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-h34w-w3vx-crw8
    aliases:
      - CVE-2025-27144
      - GHSA-c6gw-w398-hv78
    events:
      - timestamp: 2025-03-06T04:24:59Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: ce27ddb545fda01a
            componentName: github.com/go-jose/go-jose/v4
            componentVersion: v4.0.4
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype

  - id: CGA-jvcw-vg7q-4795
    aliases:
      - CVE-2024-41110
      - GHSA-v23v-6jw2-98fq
    events:
      - timestamp: 2024-07-31T07:03:49Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 1cc04d61ce71f8c1
            componentName: github.com/docker/docker
            componentVersion: v27.0.3+incompatible
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-07-31T12:35:57Z
        type: fixed
        data:
          fixed-version: 3.1.1-r1

  - id: CGA-p24f-9jv3-g77w
    aliases:
      - CVE-2024-52003
      - GHSA-h924-8g65-j9wg
    events:
      - timestamp: 2025-03-06T04:24:48Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 99d8312860dd409d
            componentName: traefik-3.1
            componentVersion: 3.1.7-r0
            componentType: apk
            componentLocation: /.PKGINFO
            scanner: grype

  - id: CGA-rp58-gvqr-xmfc
    aliases:
      - CVE-2024-34156
      - GHSA-crqm-pwhx-j97f
    events:
      - timestamp: 2024-09-11T00:15:05Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 3704a7618aee5579
            componentName: stdlib
            componentVersion: go1.22.5
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-09-16T18:23:36Z
        type: fixed
        data:
          fixed-version: 3.1.3-r0

  - id: CGA-x74m-vfrf-3fx2
    aliases:
      - CVE-2025-22868
    events:
      - timestamp: 2025-03-06T04:24:50Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.1
            componentID: 167d1509f2b0cea1
            componentName: golang.org/x/oauth2
            componentVersion: v0.23.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
