name: Build and publish YAML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    name: Build and publish YAML
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/advisories'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/618116202522/locations/global/workloadIdentityPools/prod-shared-e350/providers/prod-shared-gha"
          service_account: "prod-images-ci@prod-images-c6e5.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: prod-images-c6e5

      - name: 'Check that GCloud is properly configured'
        run: |
          gcloud info
          gcloud --quiet alpha storage ls

      - name: Build the YAML database
        uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:9eedb55a334b75c4bf1c568af2efd74992582fb66b01c27f5c00b5f175ca0f37
        with:
          entrypoint: wolfictl
          args: "advisory export --advisories-repo-dir . --format yaml -o advisories.yaml"

      - name: 'Upload the YAML database to a bucket'
        run: |
          # Don't cache advisories.yaml.
          gcloud --quiet alpha storage cp \
              --cache-control=no-store \
              ${{ github.workspace }}/advisories.yaml \
              gs://wolfi-production-registry-destination/os/
