name: Build and publish secdb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    name: Build and publish security database
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/advisories'

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/618116202522/locations/global/workloadIdentityPools/prod-shared-e350/providers/prod-shared-gha"
          service_account: "prod-images-ci@prod-images-c6e5.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: prod-images-c6e5

      - name: 'Check that GCloud is properly configured'
        run: |
          gcloud info
          gcloud --quiet alpha storage ls

      - name: Build the security database
        uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:ec1c3142faa09924563595cd4ec37158a04b241dccf6e4e275d802ba229bccc4
        with:
          entrypoint: wolfictl
          args: "advisory secdb --advisories-repo-dir . --arch x86_64 --arch aarch64 -o security.json"

      - name: 'Upload the security database to a bucket'
        run: |
          # Don't cache the security.json.
          gcloud --quiet alpha storage cp \
              --cache-control=no-store \
              ${{ github.workspace }}/security.json \
              gs://wolfi-production-registry-destination/os/

      - name: Post failure notice to Slack
        uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # ratchet:rtCamp/action-slack-notify@v2.2.1
        if: ${{ failure() }}
        env:
          SLACK_ICON: http://github.com/chainguard-dev.png?size=48
          SLACK_USERNAME: guardian
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CVE }}
          SLACK_CHANNEL: 'cve'
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: Build/Publish SecDB for ${{ github.repository }} failed!
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
